import assert from 'node:assert/strict'
import test from 'node:test'
import { existsSync, readdirSync, readFileSync } from 'node:fs'

test('extension HTML loads the Vite-built React entry', () => {
  assert.ok(existsSync('package.json'), 'package.json should define the Vite build')
  assert.ok(existsSync('scripts/watch-build.mjs'), 'scripts/watch-build.mjs should drive local rebuilds without watching dist output')
  assert.ok(existsSync('src/app.tsx'), 'src/app.tsx should be the React entry source')
  assert.ok(existsSync('src/extension/background.ts'), 'src/extension/background.ts should be the service worker source')
  assert.ok(existsSync('components.json'), 'components.json should define the shadcn project setup')

  const pkg = JSON.parse(readFileSync('package.json', 'utf8'))
  const tsconfig = JSON.parse(readFileSync('tsconfig.json', 'utf8'))
  const shadcnConfig = JSON.parse(readFileSync('components.json', 'utf8'))
  assert.match(pkg.packageManager, /^pnpm@/)
  assert.equal(pkg.scripts?.['setup:hooks'], 'git config core.hooksPath .githooks')
  assert.equal(pkg.scripts?.dev, 'node scripts/watch-build.mjs')
  assert.equal(pkg.scripts?.build, 'vite build')
  assert.equal(pkg.scripts?.['build:debug'], 'vite build --sourcemap')
  assert.equal(pkg.scripts?.lint, 'eslint . --max-warnings=0')
  assert.equal(pkg.scripts?.['deps:nolyfill'], 'pnpm dlx nolyfill --pm pnpm')
  assert.match(pkg.scripts?.['test:browser'], /RUN_BROWSER_SMOKE=1/)
  assert.equal(pkg.scripts?.['verify:bundle'], 'git diff --exit-code -- extension/dist')
  assert.match(pkg.scripts?.verify, /pnpm lint/)
  assert.match(pkg.scripts?.verify, /pnpm verify:bundle/)
  assert.match(pkg.scripts?.['verify:browser'], /pnpm test:browser/)
  assert.ok(pkg.dependencies?.react)
  assert.ok(pkg.dependencies?.['react-dom'])
  assert.ok(pkg.dependencies?.['@base-ui/react'])
  assert.ok(pkg.dependencies?.['class-variance-authority'])
  assert.ok(pkg.dependencies?.foxact)
  assert.ok(pkg.devDependencies?.['@types/chrome'])
  assert.ok(pkg.devDependencies?.['@rolldown/plugin-babel'])
  assert.ok(pkg.devDependencies?.['@tailwindcss/vite'])
  assert.ok(pkg.devDependencies?.['@iconify-json/ooui'])
  assert.ok(pkg.devDependencies?.['babel-plugin-react-compiler'])
  assert.ok(pkg.devDependencies?.tailwindcss)
  assert.ok(pkg.devDependencies?.vite)
  assert.ok(pkg.devDependencies?.shadcn)
  assert.ok(tsconfig.compilerOptions?.types?.includes('chrome'))
  assert.equal(tsconfig.compilerOptions?.allowJs, false)
  assert.equal(tsconfig.compilerOptions?.noImplicitAny, true)
  assert.equal(tsconfig.compilerOptions?.strictNullChecks, true)
  assert.deepEqual(tsconfig.compilerOptions?.paths?.['@/*'], ['./src/*'])
  assert.equal(shadcnConfig.style, 'base-nova')
  assert.equal(shadcnConfig.rsc, false)
  assert.equal(shadcnConfig.tsx, true)
  assert.equal(shadcnConfig.tailwind?.css, 'src/styles/app.css')
  assert.equal(shadcnConfig.tailwind?.config, '')
  assert.equal(shadcnConfig.tailwind?.cssVariables, true)
  assert.equal(shadcnConfig.aliases?.ui, '@/components/ui')
  assert.equal(shadcnConfig.aliases?.components, '@/components')
  assert.equal(shadcnConfig.aliases?.utils, '@/lib/utils')
  assert.equal(shadcnConfig.aliases?.lib, '@/lib')

  const indexHtml = readFileSync('extension/index.html', 'utf8')
  assert.match(indexHtml, /href="dist\/assets\/app\.css"/)
  assert.match(indexHtml, /src="dist\/app\.js"/)
  assert.doesNotMatch(indexHtml, /src="app\.js"/)

  const manifest = JSON.parse(readFileSync('extension/manifest.json', 'utf8'))
  assert.equal(manifest.background?.service_worker, 'dist/background.js')

  const viteConfig = readFileSync('vite.config.ts', 'utf8')
  const watchScript = readFileSync('scripts/watch-build.mjs', 'utf8')
  assert.match(viteConfig, /reactCompilerPreset/)
  assert.match(viteConfig, /@rolldown\/plugin-babel/)
  assert.match(viteConfig, /@tailwindcss\/vite/)
  assert.match(viteConfig, /alias:\s*\{\n\s+'@': resolve\(__dirname, 'src'\)/)
  assert.match(viteConfig, /src\/extension\/background\.ts/)
  assert.match(watchScript, /WATCH_TARGETS/)
  assert.match(watchScript, /POLL_MS/)
  assert.doesNotMatch(watchScript, /extension\/dist/)
  assert.doesNotMatch(watchScript, /\bwatch\(/)

  const appSource = readFileSync('src/app.tsx', 'utf8')
  const appStylesheet = readFileSync('src/styles/app.css', 'utf8')
  const appComponentSource = readFileSync('src/components/App.tsx', 'utf8')
  const baseStylesheet = readFileSync('extension/base.css', 'utf8')
  const domainCardSource = readFileSync('src/components/DomainCard.tsx', 'utf8')
  const domainCardContextSource = readFileSync('src/components/DomainCardContext.tsx', 'utf8')
  const flatSectionSource = readFileSync('src/components/FlatSection.tsx', 'utf8')
  const pageChipSource = readFileSync('src/components/PageChip.tsx', 'utf8')
  const pathgroupSectionSource = readFileSync('src/components/PathgroupSection.tsx', 'utf8')
  const subdomainSectionSource = readFileSync('src/components/SubdomainSection.tsx', 'utf8')
  const tabHistoryPanelSource = readFileSync('src/components/TabHistoryPanel.tsx', 'utf8')
  const headerBarSource = readFileSync('src/components/HeaderBar.tsx', 'utf8')
  const toastSource = readFileSync('src/components/Toast.tsx', 'utf8')
  const mountToastSource = readFileSync('src/components/mountToast.tsx', 'utf8')
  const buttonSource = readFileSync('src/components/ui/button.tsx', 'utf8')
  const buttonVariantsSource = readFileSync('src/components/ui/button-variants.ts', 'utf8')
  const contextMenuSource = readFileSync('src/components/ui/context-menu.tsx', 'utf8')
  const inputSource = readFileSync('src/components/ui/input.tsx', 'utf8')
  const tabsSource = readFileSync('src/components/ui/tabs.tsx', 'utf8')
  const uiFiles = readdirSync('src/components/ui').sort()
  const selectSource = readFileSync('src/components/ui/select.tsx', 'utf8')
  const tooltipSource = readFileSync('src/components/ui/tooltip.tsx', 'utf8')
  const utilsSource = readFileSync('src/lib/utils.ts', 'utf8')
  const sharedTypesSource = readFileSync('src/extension/types.d.ts', 'utf8')
  assert.match(appSource, /styles\/app\.css/)
  assert.doesNotMatch(
    [appComponentSource, domainCardSource, pageChipSource, tabHistoryPanelSource].join('\n'),
    /text-\[11px\]/
  )
  assert.match(`${appComponentSource}\n${toastSource}\n${mountToastSource}`, /react-dom\/client/)
  assert.match(buttonSource, /@base-ui\/react\/button/)
  assert.match(`${buttonSource}\n${buttonVariantsSource}`, /class-variance-authority/)
  assert.match(buttonSource, /data-slot="button"/)
  assert.match(buttonSource, /buttonVariants/)
  assert.match(buttonVariantsSource, /variant:\s*'default'/)
  assert.doesNotMatch(`${buttonSource}\n${buttonVariantsSource}`, /unstyled: ''/)
  assert.doesNotMatch(buttonSource, /type = 'button'/)
  assert.match(contextMenuSource, /activeContextMenuId/)
  assert.match(contextMenuSource, /function isContextMenuOpen\(\)/)
  assert.match(contextMenuSource, /isContextMenuOpen/)
  assert.match(contextMenuSource, /onOpenChange=\{handleOpenChange\}/)
  assert.match(contextMenuSource, /ContextMenuPrimitive\.Backdrop/)
  assert.match(contextMenuSource, /data-slot="context-menu-backdrop"/)
  assert.match(contextMenuSource, /fixed inset-0 z-\[60\]/)
  assert.match(contextMenuSource, /className="isolate z-\[70\]"/)
  assert.match(contextMenuSource, /relative isolate z-\[70\] min-w-40/)
  assert.match(contextMenuSource, /onPointerDown=\{stopBackdropEvent\}/)
  assert.match(contextMenuSource, /onClick=\{stopBackdropEvent\}/)
  assert.match(contextMenuSource, /rounded-xl bg-popover p-1/)
  assert.match(contextMenuSource, /min-h-6 min-w-36/)
  assert.match(contextMenuSource, /gap-1\.5 rounded-lg px-2 py-1 text-\[13px\]/)
  assert.match(inputSource, /@base-ui\/react\/input/)
  assert.match(inputSource, /data-slot="input"/)
  assert.match(inputSource, /focus-visible:border-ring/)
  assert.match(tabsSource, /@base-ui\/react\/tabs/)
  assert.match(tabsSource, /data-slot="tabs"/)
  assert.match(tabsSource, /data-slot="tabs-list"/)
  assert.match(tabsSource, /data-slot="tabs-trigger"/)
  assert.doesNotMatch(tabsSource, /TabsIndicator/)
  assert.match(tooltipSource, /@base-ui\/react\/tooltip/)
  assert.match(tooltipSource, /import \{ isContextMenuOpen \} from '\.\/context-menu'/)
  assert.match(tooltipSource, /data-slot="tooltip-content"/)
  assert.match(tooltipSource, /TOOLTIP_INITIAL_REST_DELAY_MS = 500/)
  assert.match(tooltipSource, /TOOLTIP_ADJACENT_REST_DELAY_MS = 180/)
  assert.match(tooltipSource, /TOOLTIP_ADJACENT_REST_WINDOW_MS = 700/)
  assert.match(tooltipSource, /TOOLTIP_HOVERABLE_CLOSE_DELAY_MS = 160/)
  assert.match(tooltipSource, /TOOLTIP_HOVER_WATCH_INTERVAL_MS = 80/)
  assert.doesNotMatch(tooltipSource, /TooltipPrimitive\.Provider/)
  assert.match(tooltipSource, /disableHoverablePopup = false/)
  assert.match(tooltipSource, /trackCursorAxis = 'none'/)
  assert.match(tooltipSource, /tooltipOpen/)
  assert.match(tooltipSource, /open=\{tooltipOpen\}/)
  assert.match(tooltipSource, /setTooltipOpen\(false\)/)
  assert.match(tooltipSource, /window\.addEventListener\('scroll', handleScroll, true\)/)
  assert.match(tooltipSource, /window\.removeEventListener\('scroll', handleScroll, true\)/)
  assert.match(tooltipSource, /window\.addEventListener\('blur', handleWindowBlur\)/)
  assert.match(tooltipSource, /window\.removeEventListener\('blur', handleWindowBlur\)/)
  assert.match(tooltipSource, /foxact\/merge-refs/)
  assert.match(tooltipSource, /foxact\/use-retimer/)
  assert.doesNotMatch(tooltipSource, /foxact\/use-page-visibility/)
  assert.doesNotMatch(tooltipSource, /usePageVisibility/)
  assert.match(tooltipSource, /const handleVisibilityChange = \(\) => \{[\s\S]*document\.visibilityState !== 'visible'[\s\S]*closeTooltip\(\)/)
  assert.match(tooltipSource, /document\.addEventListener\('visibilitychange', handleVisibilityChange\)/)
  assert.match(tooltipSource, /document\.removeEventListener\('visibilitychange', handleVisibilityChange\)/)
  assert.match(tooltipSource, /latestPointerPointRef/)
  assert.match(tooltipSource, /retimeHoverOpen/)
  assert.match(tooltipSource, /retimeHoverClose/)
  assert.match(tooltipSource, /hoverCloseScheduledRef/)
  assert.match(tooltipSource, /onOpenChange\?: \(open: boolean\) => void/)
  assert.match(tooltipSource, /onOpenChange\?\.\(true\)/)
  assert.match(tooltipSource, /onOpenChange\?\.\(false\)/)
  assert.match(tooltipSource, /pointerFocusedRef/)
  assert.match(tooltipSource, /popupPointerInsideRef/)
  assert.match(tooltipSource, /shouldUseAdjacentTooltipDelay/)
  assert.match(tooltipSource, /onPointerEnter=\{handleContentPointerEnter\}/)
  assert.match(tooltipSource, /onPointerLeave=\{handleContentPointerLeave\}/)
  assert.match(tooltipSource, /onMouseEnter=\{handleContentMouseEnter\}/)
  assert.match(tooltipSource, /onMouseLeave=\{handleContentMouseLeave\}/)
  assert.match(tooltipSource, /pointerInsideRef\.current \|\| popupPointerInsideRef\.current/)
  assert.match(tooltipSource, /setTooltipWheelPassthrough/)
  assert.match(tooltipSource, /startTooltipWheelForwarding/)
  assert.match(tooltipSource, /handleTooltipWheelForward/)
  assert.match(tooltipSource, /tooltipWheelForwardRefresh\?\.\(\)/)
  assert.match(tooltipSource, /TOOLTIP_WHEEL_TARGET_RELEASE_DELAY_MS = 320/)
  assert.match(tooltipSource, /data-tooltip-wheel-closing/)
  assert.match(tooltipSource, /window\.addEventListener\('wheel', handleTooltipWheelForward/)
  assert.match(tooltipSource, /target\.style\.setProperty\('pointer-events', 'none'\)/)
  assert.match(tooltipSource, /TOOLTIP_WHEEL_CLOSE_REOPEN_BLOCK_MS = 900/)
  assert.match(tooltipSource, /if \(!hoverCloseScheduledRef\.current\) \{[\s\S]*scheduleHoverClose\(\)/)
  assert.match(tooltipSource, /if \(isContextMenuOpen\(\)\) \{[\s\S]*clearHoverCloseTimer\(\)[\s\S]*return[\s\S]*\}/)
  assert.match(tooltipSource, /matches\(':hover'\)/)
  assert.match(tooltipSource, /document\.addEventListener\('mousemove', handlePointerOrMouseMove, true\)/)
  assert.match(tooltipSource, /!pointerFocusedRef\.current[\s\S]*triggerElement\?\.contains\(activeElement\)/)
  assert.match(tooltipSource, /const focusVisible = event\.currentTarget\.matches\(':focus-visible'\)/)
  assert.match(tooltipSource, /pointerFocusedRef\.current = !focusVisible/)
  assert.match(tooltipSource, /if \(!focusVisible\) return/)
  assert.match(tooltipSource, /onPointerDown: handlePointerDown/)
  assert.match(tooltipSource, /if \(event\.button !== 0 \|\| event\.ctrlKey\) return/)
  assert.match(tooltipSource, /onPointerLeave: handlePointerLeave/)
  assert.match(tooltipSource, /<TooltipTrigger render=\{trigger\} disabled/)
  assert.match(tooltipSource, /onClick\?\.\(event\)[\s\S]*event\.stopPropagation\(\)/)
  assert.match(tooltipSource, /onPointerDown\?\.\(event\)[\s\S]*event\.stopPropagation\(\)/)
  assert.match(tooltipSource, /TOOLTIP_CLOSE_ANCHOR_CLEAR_DELAY_MS = 200/)
  assert.match(tooltipSource, /retimeFrozenPointerClear/)
  assert.match(tooltipSource, /'children' \| 'content'/)
  assert.match(tooltipSource, /anchorToCursor\?: boolean/)
  assert.match(tooltipSource, /anchorToCursor = true/)
  assert.match(tooltipSource, /new DOMRect\(frozenPointerPoint\.x, frozenPointerPoint\.y, 0, 0\)/)
  assert.match(tooltipSource, /const tooltipAnchor = anchorToCursor \? cursorAnchor : undefined/)
  assert.match(tooltipSource, /positionMethod=\{tooltipAnchor \? 'fixed' : undefined\}/)
  assert.match(tooltipSource, /side = 'bottom'/)
  assert.match(tooltipSource, /align = 'start'/)
  assert.match(tooltipSource, /instant = false/)
  assert.match(tooltipSource, /openInstantly: contentProps\.instant === true/)
  assert.match(tooltipSource, /if \(openInstantly\) \{[\s\S]*openTooltip\(point\)[\s\S]*return[\s\S]*\}/)
  assert.match(tooltipSource, /if \(closeInstantly\) \{[\s\S]*closeTooltip\(\)[\s\S]*return[\s\S]*\}/)
  assert.match(tooltipSource, /document\.elementFromPoint\(point\.x, point\.y\)/)
  assert.match(tooltipSource, /instant\s*\?\s*'transition-none'/)
  assert.match(tooltipSource, /TOOLTIP_EDGE_BORDER_ALIGN_OFFSET_PX = 1/)
  assert.match(tooltipSource, /alignOffset = TOOLTIP_EDGE_BORDER_ALIGN_OFFSET_PX/)
  assert.match(tooltipSource, /sideOffset = 16/)
  assert.match(tooltipSource, /arrowPadding = 0/)
  assert.match(tooltipSource, /collisionPadding = 0/)
  assert.match(tooltipSource, /TOOLTIP_COLLISION_AVOIDANCE/)
  assert.match(tooltipSource, /align: 'flip'/)
  assert.match(tooltipSource, /rounded-\[10px\]/)
  assert.match(tooltipSource, /data-\[align=start\]:data-\[side=bottom\]:rounded-tl-none/)
  assert.match(tooltipSource, /data-\[align=end\]:data-\[side=bottom\]:rounded-tr-none/)
  assert.match(tooltipSource, /\[overflow-wrap:anywhere\]/)
  assert.match(tooltipSource, /bg-\[canvas\]/)
  assert.doesNotMatch(tooltipSource, /TooltipPrimitive\.Arrow/)
  assert.doesNotMatch(tooltipSource, /function ArrowSvg/)
  assert.match(tooltipSource, /TooltipAnchor/)
  assert.match(tooltipSource, /tooltipScrollableAncestors/)
  assert.match(tooltipSource, /tooltipScrollableAncestorsUnderPoint/)
  assert.match(tooltipSource, /document\.elementFromPoint\(x, y\)/)
  assert.match(tooltipSource, /uniqueTooltipScrollableAncestors/)
  assert.match(tooltipSource, /handleContentWheelRef/)
  assert.match(tooltipSource, /popupElement\.addEventListener\('wheel', handleWheel, \{\s*passive: false\s*\}\)/)
  assert.match(tooltipSource, /popupElement\.removeEventListener\('wheel', handleWheel\)/)
  assert.doesNotMatch(tooltipSource, /onWheel=\{handleContentWheel\}/)
  assert.match(pageChipSource, /useReducer\(chipLayoutReducer, DEFAULT_CHIP_LAYOUT_STATE\)/)
  assert.match(pageChipSource, /type: 'tooltipLayout'/)
  assert.match(pageChipSource, /chipTextTruncationCallbacks/)
  assert.match(pageChipSource, /getBoundingClientRect\(\)\.width/)
  assert.match(pageChipSource, /getBoundingClientRect\(\)\.height/)
  assert.match(pageChipSource, /PAGE_CHIP_TOOLTIP_TEXT_LEFT_INSET_PX = 6/)
  assert.match(pageChipSource, /PAGE_CHIP_TOOLTIP_TEXT_RIGHT_INSET_PX = 8/)
  assert.match(pageChipSource, /paddingLeft: `\$\{PAGE_CHIP_TOOLTIP_TEXT_LEFT_INSET_PX\}px`/)
  assert.match(pageChipSource, /paddingRight: `\$\{PAGE_CHIP_TOOLTIP_TEXT_RIGHT_INSET_PX\}px`/)
  assert.match(pageChipSource, /anchorToCursor=\{false\}/)
  assert.match(pageChipSource, /roundToDevicePixel/)
  assert.match(pageChipSource, /getChipTooltipSubpixelOffset/)
  assert.match(pageChipSource, /chipTooltipSubpixelOffset/)
  assert.match(pageChipSource, /translate3d\(\$\{chipTooltipSubpixelOffset\.x\}px, \$\{chipTooltipSubpixelOffset\.y\}px, 0\)/)
  assert.match(pageChipSource, /getChipTooltipAnchor/)
  assert.match(pageChipSource, /const left = rect\.left - PAGE_CHIP_TOOLTIP_TEXT_LEFT_INSET_PX/)
  assert.match(pageChipSource, /const top = rect\.top - PAGE_CHIP_TOOLTIP_TEXT_TOP_INSET_PX/)
  assert.match(pageChipSource, /new DOMRect\(left, top, popupWidth, 0\)/)
  assert.match(pageChipSource, /chip-text-tooltip-hit-area -my-\[5px\][\s\S]*py-\[5px\]/)
  assert.match(pageChipSource, /const titleVariantTitleTooltipTriggerElement = \(/)
  assert.match(pageChipSource, /<TooltipAnchor[\s\S]*content=\{chipTooltipContent\}[\s\S]*\{titleVariantTitleTooltipTriggerElement\}/)
  assert.doesNotMatch(pageChipSource, /titleVariantTooltipContentNode/)
  assert.match(pageChipSource, /<TooltipAnchor[\s\S]*anchor=\{getChipTooltipAnchor\}[\s\S]*anchorToCursor=\{false\}[\s\S]*\binstant[\s\S]*sideOffset=\{0\}/)
  assert.match(pageChipSource, /page-chip-tooltip-open/)
  assert.match(pageChipSource, /onOpenChange=\{setChipTooltipOpen\}/)
  assert.match(pageChipSource, /\[\&\.page-chip-tooltip-open\]:bg-\[rgba\(82,82,82,0\.13\)\]/)
  assert.match(pageChipSource, /--page-chip-tooltip-text-width/)
  assert.match(pageChipSource, /--page-chip-tooltip-width/)
  assert.match(pageChipSource, /--page-chip-tooltip-max-width/)
  assert.match(pageChipSource, /PAGE_CHIP_TOOLTIP_VIEWPORT_MARGIN_PX = 8/)
  assert.match(pageChipSource, /getRegularChipTooltipWidth/)
  assert.match(pageChipSource, /getRegularChipTooltipLineHtml/)
  assert.match(pageChipSource, /hydrateClonedChipTooltipFragment/)
  assert.match(pageChipSource, /PAGE_CHIP_TOOLTIP_SUPPRESSION_MARKER_CLASS_NAME/)
  assert.match(pageChipSource, /ensureLeadingTooltipMarkerSpace/)
  assert.match(pageChipSource, /whitespace-nowrap/)
  assert.match(pageChipSource, /fixedLineOverflows/)
  assert.match(pageChipSource, /tooltipLineContentOverflows/)
  assert.match(pageChipSource, /PAGE_CHIP_TOOLTIP_CONSTRAINED_LINE_CLASS_NAME/)
  assert.match(pageChipSource, /chipTooltipViewportConstrained/)
  assert.match(pageChipSource, /markerWrapsTaller/)
  assert.match(pageChipSource, /paintedRangeRect/)
  assert.match(pageChipSource, /PAGE_CHIP_TOOLTIP_TAIL_LINE_CLASS_NAME/)
  assert.match(pageChipSource, /page-chip-tooltip-measure/)
  assert.match(pageChipSource, /page-chip-tooltip-line/)
  assert.match(pageChipSource, /tooltipLineNodesFromHtml/)
  assert.doesNotMatch(pageChipSource, /dangerouslySetInnerHTML/)
  assert.match(pageChipSource, /chipTextContentNode\(mode: ChipTextRenderMode\)/)
  assert.match(pageChipSource, /chipTextContentNode\('tooltip'\)/)
  assert.match(pageChipSource, /chipTextContentNode\('chip'\)/)
  assert.match(pageChipSource, /page-chip-tooltip max-w-\[calc\(100vw-16px\)\] text-\[13px\] leading-tight \[overflow-wrap:break-word\]/)
  assert.match(pageChipSource, /w-\[var\(--page-chip-tooltip-width\)\]/)
  assert.match(pageChipSource, /w-\[var\(--page-chip-tooltip-text-width\)\]/)
  assert.match(pageChipSource, /whitespace-normal hyphens-auto break-normal/)
  assert.match(pageChipSource, /inline-block max-w-\[calc\(100%-6px\)\] whitespace-normal break-normal \[width:max-content\] \[overflow-wrap:break-word\]/)
  assert.doesNotMatch(pageChipSource, /duplicateLabel \|\| activeLabel/)
  assert.doesNotMatch(pageChipSource, /\? chip\.tooltip : undefined/)
  assert.doesNotMatch(pageChipSource, /@chenglou\/pretext/)
  assert.match(tabHistoryPanelSource, /historyTitleTruncationCallbacks/)
  assert.match(tabHistoryPanelSource, /HISTORY_TITLE_TOOLTIP_TEXT_LEFT_INSET_PX = 6/)
  assert.match(tabHistoryPanelSource, /HISTORY_TITLE_TOOLTIP_TEXT_TOP_INSET_PX = 4/)
  assert.match(tabHistoryPanelSource, /HISTORY_TITLE_TOOLTIP_HORIZONTAL_PADDING_PX/)
  assert.match(tabHistoryPanelSource, /useState<HistoryTitleMetrics>/)
  assert.match(tabHistoryPanelSource, /titleEl\.scrollHeight - titleEl\.clientHeight > 1/)
  assert.match(tabHistoryPanelSource, /getHistoryTitleContentWidth/)
  assert.match(tabHistoryPanelSource, /getHistoryTitleTooltipLineHtml/)
  assert.match(tabHistoryPanelSource, /historyTitleTooltipLineMarkup/)
  assert.match(tabHistoryPanelSource, /historyTitleTooltipLineNodesFromHtml/)
  assert.match(tabHistoryPanelSource, /tooltipViewportConstrained/)
  assert.match(tabHistoryPanelSource, /visibleLineCount/)
  assert.match(tabHistoryPanelSource, /getBoundingClientRect\(\)\.width/)
  assert.match(tabHistoryPanelSource, /function getHistoryTitleTooltipAnchor\(\)/)
  assert.match(tabHistoryPanelSource, /const left = rect\.left - HISTORY_TITLE_TOOLTIP_TEXT_LEFT_INSET_PX/)
  assert.match(tabHistoryPanelSource, /new DOMRect\(left, top, popupWidth, 0\)/)
  assert.match(tabHistoryPanelSource, /--history-entry-title-tooltip-text-width/)
  assert.match(tabHistoryPanelSource, /titleTooltipTargetTextWidth/)
  assert.match(tabHistoryPanelSource, /titleTooltipTextWidth \+ HISTORY_TITLE_TOOLTIP_HORIZONTAL_PADDING_PX/)
  assert.match(tabHistoryPanelSource, /roundHistoryTitleTooltipToDevicePixel/)
  assert.match(tabHistoryPanelSource, /getHistoryTitleTooltipSubpixelOffset/)
  assert.match(tabHistoryPanelSource, /historyTitleTooltipSubpixelOffset/)
  assert.match(tabHistoryPanelSource, /translate3d\(\$\{titleMetrics\.tooltipSubpixelOffset\.x\}px, \$\{titleMetrics\.tooltipSubpixelOffset\.y\}px, 0\)/)
  assert.match(tabHistoryPanelSource, /const \[titleTooltipOpen, setTitleTooltipOpen\] = useState\(false\)/)
  assert.match(tabHistoryPanelSource, /titleTooltipOpen && 'history-entry-tooltip-open'/)
  assert.match(tabHistoryPanelSource, /titleTooltipOpen && 'history-entry-row-tooltip-open'/)
  assert.match(tabHistoryPanelSource, /history-entry-low-score opacity-60 hover:opacity-100 focus-within:opacity-100 \[\&\.history-entry-row-tooltip-open\]:opacity-100/)
  assert.match(tabHistoryPanelSource, /group-\[\.history-entry-row-tooltip-open\]\/history-row:text-\[rgba\(115,115,115,0\.54\)\]/)
  assert.match(tabHistoryPanelSource, /function onHistoryTitleTooltipClick\(e: MouseEvent<HTMLDivElement>\)/)
  assert.match(tabHistoryPanelSource, /className="history-entry-title-tooltip max-w-\[calc\(100vw-16px\)\] text-\[13px\] leading-tight \[overflow-wrap:break-word\] cursor-default select-none"/)
  assert.match(tabHistoryPanelSource, /onClick=\{onHistoryTitleTooltipClick\}/)
  assert.match(tabHistoryPanelSource, /history-entry-title-tooltip-hit-area/)
  assert.match(tabHistoryPanelSource, /\[\&\.history-entry-tooltip-open\]:bg-\[rgba\(82,82,82,0\.13\)\]/)
  assert.match(tabHistoryPanelSource, /\[\&\.history-entry-tooltip-open\]:bg-\[rgba\(82,82,82,0\.18\)\]/)
  assert.match(tabHistoryPanelSource, /onOpenChange=\{setTitleTooltipOpen\}/)
  assert.match(tabHistoryPanelSource, /history-entry-title-tooltip-line-tail/)
  assert.match(tabHistoryPanelSource, /maxWidth: `calc\(100vw - \$\{titleTooltipPopupLeft\}px - 8px\)`/)
  assert.match(tabHistoryPanelSource, /const titleTooltipContent = titleMetrics\.isTruncated && entryLabel/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry-title-tooltip line-clamp-2/)
  assert.match(tabHistoryPanelSource, /w-\[var\(--history-entry-title-tooltip-text-width\)\]/)
  assert.doesNotMatch(tabHistoryPanelSource, /\[text-wrap:balance\]/)
  assert.doesNotMatch(tabHistoryPanelSource, /\[width:max-content\]/)
  assert.match(tabHistoryPanelSource, /anchorToCursor=\{false\}/)
  assert.match(tabHistoryPanelSource, /sideOffset=\{0\}/)
  assert.match(tabHistoryPanelSource, /className="history-entry-title-tooltip max-w-\[calc\(100vw-16px\)\] text-\[13px\] leading-tight \[overflow-wrap:break-word\] cursor-default select-none"/)
  assert.match(tabHistoryPanelSource, /\[overflow-wrap:break-word\]/)
  assert.match(tabHistoryPanelSource, /\[font-family:inherit\]/)
  assert.match(tabHistoryPanelSource, /focus-within:shadow-\[inset_0_0_0_1px_rgba\(234,179,8,0\.42\)\]/)
  assert.match(tabHistoryPanelSource, /history-entry group\/history-entry[^"]*rounded-\[10px\][^"]*border-0[^"]*bg-transparent/)
  assert.match(tabHistoryPanelSource, /history-entry-title block min-w-0 flex-auto overflow-hidden hyphens-auto break-normal max-h-\[calc\(2lh\)\]/)
  assert.match(tabHistoryPanelSource, /\[\&\.history-entry-title-truncated\]:\[mask-image:linear-gradient\(to_bottom,black_0,black_calc\(100%_-_1lh\),transparent_calc\(100%_-_1lh\)\),linear-gradient\(to_right,black_0,black_calc\(100%_-_60px\),rgba\(0,0,0,0\.35\)_calc\(100%_-_20px\),transparent\)\]/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry-title line-clamp-2/)
  assert.match(tabHistoryPanelSource, /group-hover\/history-row:bg-\[rgba\(82,82,82,0\.13\)\]/)
  assert.doesNotMatch(tabHistoryPanelSource, /border border-\[var\(--warm-gray\)\]/)
  assert.doesNotMatch(tabHistoryPanelSource, /group-hover\/history-row:border-\[var\(--accent-amber\)\]/)
  assert.match(tabHistoryPanelSource, /after:w-0/)
  assert.doesNotMatch(tabHistoryPanelSource, /after:w-14/)
  assert.match(tabHistoryPanelSource, /className="history-entry-main flex min-h-8\.5[^"]*cursor-default[^"]*items-start[^"]*focus-visible:outline-none/)
  assert.match(tabHistoryPanelSource, /className="history-entry-close history-entry-close-favicon pointer-events-none absolute[^"]*group-hover\/history-favicon-frame:pointer-events-auto[^"]*focus-visible:outline-2/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry group\/history-entry[^"]*\btransition-/)
  assert.doesNotMatch(tabHistoryPanelSource, /className="history-entry-close history-entry-close-favicon[^"]*\btransition-/)
  assert.doesNotMatch(tabHistoryPanelSource, /<TooltipAnchor content=\{entryLabel\}>/)
  assert.match(pathgroupSectionSource, /pathgroupLabelTruncated \? \(/)
  assert.match(pathgroupSectionSource, /className="text-\[13px\] leading-tight"/)
  assert.doesNotMatch(pathgroupSectionSource, /<TooltipAnchor content=\{displayLabel\}>/)
  assert.match(tooltipSource, /mergeRefs<HTMLElement>\(children\.props\.ref, triggerElementRef\)/)
  assert.match(tooltipSource, /children\.props\.ref/)
  assert.match(selectSource, /@base-ui\/react\/select/)
  assert.match(selectSource, /lucide-react/)
  assert.match(selectSource, /@\/lib\/utils/)
  assert.match(utilsSource, /import \{ clsx, type ClassValue \} from 'clsx'/)
  assert.match(utilsSource, /import \{ twMerge \} from 'tailwind-merge'/)
  assert.match(utilsSource, /export function cn/)
  assert.equal(existsSync('src/lib/cn.ts'), false)
  assert.match(appStylesheet, /--color-input:/)
  assert.match(appStylesheet, /--color-popover:/)
  assert.match(appStylesheet, /--color-popover-foreground:/)
  assert.match(appStylesheet, /--color-ring:/)
  assert.match(selectSource, /data-slot="select-trigger"/)
  assert.match(selectSource, /data-size=\{size\}/)
  assert.match(selectSource, /border-input bg-transparent py-2 pr-2 pl-2\.5 text-sm whitespace-nowrap transition-colors/)
  assert.match(selectSource, /data-placeholder:text-muted-foreground/)
  assert.match(selectSource, /data-slot="select-content"/)
  assert.match(selectSource, /max-h-\(--available-height\) w-\(--anchor-width\) min-w-36/)
  assert.match(selectSource, /SelectPrimitive\.ScrollUpArrow/)
  assert.match(selectSource, /SelectPrimitive\.ScrollDownArrow/)
  assert.match(selectSource, /SelectPrimitive\.ItemIndicator/)
  assert.match(selectSource, /SelectPrimitive\.ItemText className="flex flex-1 shrink-0 gap-2 whitespace-nowrap"/)
  assert.match(selectSource, /pointer-events-none absolute right-2 flex size-4 items-center justify-center/)
  assert.match(selectSource, /ChevronDownIcon/)
  assert.match(selectSource, /ChevronUpIcon/)
  assert.match(selectSource, /data-slot="select-scroll-up-button"/)
  assert.match(selectSource, /data-slot="select-scroll-down-button"/)
  assert.match(selectSource, /align = 'center'/)
  assert.match(selectSource, /alignItemWithTrigger = true/)
  assert.match(selectSource, /data-align-trigger/)
  assert.doesNotMatch(headerBarSource, /from '\.\/ui\/button'/)
  assert.match(headerBarSource, /from '\.\/ui\/input'/)
  assert.match(headerBarSource, /from '\.\/ui\/select'/)
  assert.match(headerBarSource, /from '\.\/ui\/tabs'/)
  assert.match(headerBarSource, /function HistoryRangeSelect/)
  assert.match(headerBarSource, /<Select value=\{value\} items=\{HISTORY_RANGE_OPTIONS\} onValueChange=\{handleValueChange\}>/)
  assert.match(headerBarSource, /<SelectContent[\s\S]*align="start"[\s\S]*alignItemWithTrigger=\{false\}/)
  assert.match(headerBarSource, /<SelectGroup>/)
  assert.match(headerBarSource, /<SelectItem[\s\S]*key=\{option\.value\}[\s\S]*value=\{option\.value\}[\s\S]*label=\{option\.label\}/)
  assert.doesNotMatch(headerBarSource, /SelectControl|TextInput|SegmentedTabs/)
  assert.deepEqual(uiFiles, ['button-variants.ts', 'button.tsx', 'context-menu.tsx', 'input.tsx', 'select.tsx', 'tabs-variants.ts', 'tabs.tsx', 'tooltip.tsx'])
  assert.match(toastSource, /p-4!/)
  assert.match(toastSource, /mt-2!/)
  assert.match(toastSource, /px-3!/)
  assert.match(toastSource, /fixed bottom-4 left-4 right-auto top-auto/)
  assert.match(toastSource, /min-\[500px\]:left-8/)
  assert.match(toastSource, /origin-\[bottom_center\]/)
  assert.doesNotMatch(toastSource, /origin-\[bottom_left\]/)
  assert.doesNotMatch(toastSource, /min-\[500px\]:right-8/)
  assert.match(toastSource, /rounded-3xl \[corner-shape:squircle\]/)
  assert.match(toastSource, /<BaseToast\.Content className="[^"]*data-behind:opacity-0/)
  assert.match(toastSource, /rounded-xl \[corner-shape:squircle\]/)
  assert.match(toastSource, /rounded-full border-0 bg-transparent/)
  assert.match(toastSource, /<XIcon className="size-3" \/>/)
  assert.match(toastSource, /\[corner-shape:squircle\]/)
  assert.doesNotMatch(toastSource, /rounded-sm/)
  assert.match(baseStylesheet, /button,\ninput,\nselect,\ntextarea\s*\{\n\s*font-family: inherit;/)
  assert.match(baseStylesheet, /\.scroll-region\s*\{[\s\S]*overflow-y: auto;[\s\S]*overflow-x: hidden;[\s\S]*overscroll-behavior-y: contain;[\s\S]*overscroll-behavior-x: none;/)
  assert.match(pageChipSource, /'chip-dupe-badge [^']*items-start[^']*px-0[^']*pt-px/)
  assert.match(pageChipSource, /dupeCount > 9 && 'chip-dupe-badge-wide [^']*px-1/)
  assert.match(pageChipSource, /dedupeBadgesClosing && 'closing'/)
  assert.match(domainCardContextSource, /createContext\(defaultDomainCardContext\)/)
  assert.match(domainCardSource, /<DomainCardProvider value=\{cardContext\}>/)
  assert.match(appComponentSource, /const \[hoverMatch, setHoverMatch\] = useState/)
  assert.match(appComponentSource, /useState<HoverMatchState>\(\{ url: '', urls: \[\], source: null \}\)/)
  assert.match(appComponentSource, /function sameHoverUrls/)
  assert.match(appComponentSource, /function handleHoverUrlChange\(url: string, source: HoverUrlSource = 'chip', matchUrls\?: readonly string\[\]\)/)
  assert.match(appComponentSource, /setHoverMatch/)
  assert.match(appComponentSource, /setUrlPreview\(nextUrl\)/)
  assert.match(appComponentSource, /activeHoverUrl=\{hoverMatch\.url\}/)
  assert.match(appComponentSource, /activeHoverUrls=\{hoverMatch\.urls\}/)
  assert.match(appComponentSource, /activeHoverSource=\{hoverMatch\.source\}/)
  assert.match(`${flatSectionSource}\n${pageChipSource}\n${pathgroupSectionSource}\n${subdomainSectionSource}`, /useDomainCardContext/)
  assert.doesNotMatch(`${flatSectionSource}\n${pathgroupSectionSource}\n${subdomainSectionSource}`, /dedupeBadgesClosing\?:|onActiveSuppressedTitleChange\?:|onHoverUrlChange\?:|onLayoutChange\?:/)
  assert.doesNotMatch(domainCardSource, /querySelectorAll/)
  assert.doesNotMatch(`${appSource}\n${appComponentSource}\n${toastSource}`, /vendor\/preact|vendor\/htm/)
  assert.doesNotMatch(sharedTypesSource, /const chrome:\s*any/)
  assert.doesNotMatch(sharedTypesSource, /LOCAL_PATH_GROUPERS\?:\s*any\[\]/)
})

test('repo pre-commit hook runs the verification pipeline', () => {
  assert.ok(existsSync('.githooks/pre-commit'), 'pre-commit hook should be committed for local setup')

  const hook = readFileSync('.githooks/pre-commit', 'utf8')
  assert.match(hook, /^#!\/bin\/sh/)
  assert.match(hook, /pnpm verify/)
})

test('built extension bundle is packaged locally', () => {
  assert.ok(existsSync('extension/dist/app.js'), 'extension/dist/app.js should be committed build output for unpacked extension loading')
  assert.ok(existsSync('extension/dist/background.js'), 'extension/dist/background.js should be committed service worker output')
  assert.equal(existsSync('extension/dist/app.js.map'), false, 'production build should not ship a sourcemap')
  assert.equal(existsSync('extension/dist/background.js.map'), false, 'production build should not ship a service-worker sourcemap')
  assert.equal(existsSync('extension/dist/chunks'), false, 'dashboard UI should be bundled into one JS entry')
  assert.ok(existsSync('extension/dist/assets/app.css'), 'extension/dist/assets/app.css should be committed stylesheet output')

  const distFiles = readdirSync('extension/dist').sort()
  assert.deepEqual(distFiles, ['app.js', 'assets', 'background.js'])
  assert.deepEqual(readdirSync('extension/dist/assets').sort(), ['app.css'])
  assert.deepEqual(readdirSync('extension').filter((name) => name.endsWith('.js')), ['config.local.js'])

  const bundle = readFileSync('extension/dist/app.js', 'utf8')
  const backgroundBundle = readFileSync('extension/dist/background.js', 'utf8')
  const stylesheet = readFileSync('extension/dist/assets/app.css', 'utf8')
  assert.doesNotMatch(bundle, /from\s+['"]https?:\/\//)
  assert.doesNotMatch(backgroundBundle, /from\s+['"]https?:\/\//)
  assert.doesNotMatch(bundle, /vendor\/preact|vendor\/htm/)
  assert.match(bundle, /mission-card/)
  assert.match(stylesheet, /\.dashboard-main/)
  assert.match(stylesheet, /body\{[^}]*font-family:sans-serif/)
  assert.doesNotMatch(stylesheet, /@layer base\{/)
  assert.doesNotMatch(stylesheet, /@layer components\{/)
  assert.doesNotMatch(stylesheet, /@font-face/)
  assert.doesNotMatch(stylesheet, /url\(["']?https?:\/\//)
  assert.doesNotMatch(stylesheet, /tailwindcss\/preflight/)
})
