import assert from 'node:assert/strict'
import test from 'node:test'
import { existsSync, readdirSync, readFileSync } from 'node:fs'

test('extension HTML loads the Vite-built React entry', () => {
  assert.ok(existsSync('package.json'), 'package.json should define the Vite build')
  assert.ok(existsSync('scripts/build-extension.mjs'), 'scripts/build-extension.mjs should build extension entries without shared runtime chunks')
  assert.ok(existsSync('scripts/watch-build.mjs'), 'scripts/watch-build.mjs should drive local rebuilds without watching dist output')
  assert.ok(existsSync('src/app.tsx'), 'src/app.tsx should be the React entry source')
  assert.ok(existsSync('src/extension/background.ts'), 'src/extension/background.ts should be the service worker source')
  assert.ok(existsSync('components.json'), 'components.json should define the shadcn project setup')

  const pkg = JSON.parse(readFileSync('package.json', 'utf8'))
  const tsconfig = JSON.parse(readFileSync('tsconfig.json', 'utf8'))
  const shadcnConfig = JSON.parse(readFileSync('components.json', 'utf8'))
  assert.match(pkg.packageManager, /^pnpm@/)
  assert.equal(pkg.scripts?.['setup:hooks'], 'git config core.hooksPath .githooks')
  assert.equal(pkg.scripts?.dev, 'node scripts/watch-build.mjs')
  assert.equal(pkg.scripts?.build, 'node scripts/build-extension.mjs')
  assert.equal(pkg.scripts?.['build:debug'], 'node scripts/build-extension.mjs --sourcemap')
  assert.equal(pkg.scripts?.lint, 'eslint . --max-warnings=0')
  assert.equal(pkg.scripts?.['deps:nolyfill'], 'pnpm dlx nolyfill --pm pnpm')
  assert.match(pkg.scripts?.['test:browser'], /RUN_BROWSER_SMOKE=1/)
  assert.equal(pkg.scripts?.['verify:bundle'], 'git diff --exit-code -- extension/dist')
  assert.match(pkg.scripts?.verify, /pnpm lint/)
  assert.match(pkg.scripts?.verify, /pnpm verify:bundle/)
  assert.match(pkg.scripts?.['verify:browser'], /pnpm test:browser/)
  assert.ok(pkg.dependencies?.react)
  assert.ok(pkg.dependencies?.['react-dom'])
  assert.ok(pkg.dependencies?.['@base-ui/react'])
  assert.ok(pkg.dependencies?.['class-variance-authority'])
  assert.ok(pkg.dependencies?.foxact)
  assert.ok(pkg.devDependencies?.['@types/chrome'])
  assert.ok(pkg.devDependencies?.['@rolldown/plugin-babel'])
  assert.ok(pkg.devDependencies?.['@tailwindcss/vite'])
  assert.ok(pkg.devDependencies?.['@iconify-json/ooui'])
  assert.ok(pkg.devDependencies?.['babel-plugin-react-compiler'])
  assert.ok(pkg.devDependencies?.tailwindcss)
  assert.ok(pkg.devDependencies?.vite)
  assert.ok(pkg.devDependencies?.shadcn)
  assert.ok(tsconfig.compilerOptions?.types?.includes('chrome'))
  assert.equal(tsconfig.compilerOptions?.allowJs, false)
  assert.equal(tsconfig.compilerOptions?.noImplicitAny, true)
  assert.equal(tsconfig.compilerOptions?.strictNullChecks, true)
  assert.deepEqual(tsconfig.compilerOptions?.paths?.['@/*'], ['./src/*'])
  assert.equal(shadcnConfig.style, 'base-nova')
  assert.equal(shadcnConfig.rsc, false)
  assert.equal(shadcnConfig.tsx, true)
  assert.equal(shadcnConfig.tailwind?.css, 'src/styles/app.css')
  assert.equal(shadcnConfig.tailwind?.config, '')
  assert.equal(shadcnConfig.tailwind?.cssVariables, true)
  assert.equal(shadcnConfig.aliases?.ui, '@/components/ui')
  assert.equal(shadcnConfig.aliases?.components, '@/components')
  assert.equal(shadcnConfig.aliases?.utils, '@/lib/utils')
  assert.equal(shadcnConfig.aliases?.lib, '@/lib')

  const indexHtml = readFileSync('extension/index.html', 'utf8')
  assert.match(indexHtml, /href="dist\/assets\/app\.css"/)
  assert.match(indexHtml, /src="dist\/app\.js"/)
  assert.doesNotMatch(indexHtml, /src="app\.js"/)

  const manifest = JSON.parse(readFileSync('extension/manifest.json', 'utf8'))
  assert.equal(manifest.background?.service_worker, 'dist/background.js')

  const viteConfig = readFileSync('vite.config.ts', 'utf8')
  const buildScript = readFileSync('scripts/build-extension.mjs', 'utf8')
  const watchScript = readFileSync('scripts/watch-build.mjs', 'utf8')
  assert.match(viteConfig, /reactCompilerPreset/)
  assert.match(viteConfig, /@rolldown\/plugin-babel/)
  assert.match(viteConfig, /@tailwindcss\/vite/)
  assert.match(viteConfig, /TAB_OUT_BUILD_ENTRY/)
  assert.match(viteConfig, /codeSplitting: false/)
  assert.match(viteConfig, /alias:\s*\{\n\s+'@': resolve\(__dirname, 'src'\)/)
  assert.match(viteConfig, /src\/extension\/background\.ts/)
  assert.match(buildScript, /runBuild\('app'\)/)
  assert.match(buildScript, /runBuild\('background'\)/)
  assert.match(watchScript, /WATCH_TARGETS/)
  assert.match(watchScript, /\['build'\]/)
  assert.match(watchScript, /POLL_MS/)
  assert.doesNotMatch(watchScript, /extension\/dist/)
  assert.doesNotMatch(watchScript, /\bwatch\(/)

  const appSource = readFileSync('src/app.tsx', 'utf8')
  const appStylesheet = readFileSync('src/styles/app.css', 'utf8')
  const appComponentSource = readFileSync('src/components/App.tsx', 'utf8')
  const useHoverMatchSource = readFileSync('src/hooks/useHoverMatch.ts', 'utf8')
  const baseStylesheet = readFileSync('extension/base.css', 'utf8')
  const domainCardSource = readFileSync('src/components/DomainCard.tsx', 'utf8')
  const domainCardContextSource = readFileSync('src/components/DomainCardContext.tsx', 'utf8')
  const flatSectionSource = readFileSync('src/components/FlatSection.tsx', 'utf8')
  const pageChipSource = readFileSync('src/components/PageChip.tsx', 'utf8')
  const pageChipOverflowSource = readFileSync('src/components/PageChipOverflow.tsx', 'utf8')
  const pageTargetSource = readFileSync('src/extension/page-target.ts', 'utf8')
  const tabFocusSource = readFileSync('src/extension/tab-focus.ts', 'utf8')
  const pathgroupSectionSource = readFileSync('src/components/PathgroupSection.tsx', 'utf8')
  const subdomainSectionSource = readFileSync('src/components/SubdomainSection.tsx', 'utf8')
  const tabHistoryPanelSource = readFileSync('src/components/TabHistoryPanel.tsx', 'utf8')
  const tabHistorySource = readFileSync('src/extension/tab-history.ts', 'utf8')
  const tabHistoryServiceSource = readFileSync('src/extension/background/tab-history-service.ts', 'utf8')
  const headerBarSource = readFileSync('src/components/HeaderBar.tsx', 'utf8')
  const workingSetClientSource = readFileSync('src/extension/working-set-client.ts', 'utf8')
  const toastSource = readFileSync('src/components/Toast.tsx', 'utf8')
  const mountToastSource = readFileSync('src/components/mountToast.tsx', 'utf8')
  const buttonSource = readFileSync('src/components/ui/button.tsx', 'utf8')
  const buttonVariantsSource = readFileSync('src/components/ui/button-variants.ts', 'utf8')
  const contextMenuSource = readFileSync('src/components/ui/context-menu.tsx', 'utf8')
  const contextMenuRegistrySource = readFileSync('src/components/ui/context-menu-registry.ts', 'utf8')
  const inputSource = readFileSync('src/components/ui/input.tsx', 'utf8')
  const tabsSource = readFileSync('src/components/ui/tabs.tsx', 'utf8')
  const uiFiles = readdirSync('src/components/ui').sort()
  const selectSource = readFileSync('src/components/ui/select.tsx', 'utf8')
  const tooltipSource = readFileSync('src/components/ui/tooltip.tsx', 'utf8')
  const utilsSource = readFileSync('src/lib/utils.ts', 'utf8')
  const sharedTypesSource = readFileSync('src/extension/types.d.ts', 'utf8')
  assert.match(pageTargetSource, /export function pageTargetMatchUrls/)
  assert.match(pageTargetSource, /export function pageTargetMatchesHover/)
  assert.match(tabFocusSource, /export async function focusExistingTabTarget/)
  assert.match(tabFocusSource, /chromeApi\.runtime\.sendMessage\(extensionId, \{ action: 'unsuspend', tabId: tab\.id \}\)/)
  assert.match(tabFocusSource, /updateProperties\.url = targetEffective/)
  assert.match(tabHistorySource, /focusExistingTabTarget/)
  assert.match(workingSetClientSource, /focusExistingTabTarget/)
  assert.match(tabHistoryServiceSource, /focusExistingTabTarget/)
  assert.match(tabHistoryServiceSource, /const url = unwrapSuspenderUrl\(rawUrl\)/)
  assert.match(sharedTypesSource, /interface TabHistoryEntry[\s\S]*rawUrl: string/)
  assert.match(appSource, /styles\/app\.css/)
  assert.doesNotMatch(
    [appComponentSource, domainCardSource, pageChipSource, tabHistoryPanelSource].join('\n'),
    /text-\[11px\]/
  )
  assert.match(`${appComponentSource}\n${toastSource}\n${mountToastSource}`, /react-dom\/client/)
  assert.match(buttonSource, /@base-ui\/react\/button/)
  assert.match(`${buttonSource}\n${buttonVariantsSource}`, /class-variance-authority/)
  assert.match(buttonSource, /data-slot="button"/)
  assert.match(buttonSource, /buttonVariants/)
  assert.match(buttonVariantsSource, /variant:\s*'default'/)
  assert.doesNotMatch(`${buttonSource}\n${buttonVariantsSource}`, /unstyled: ''/)
  assert.doesNotMatch(buttonSource, /type = 'button'/)
  assert.match(contextMenuRegistrySource, /activeContextMenuId/)
  assert.match(contextMenuRegistrySource, /export function isContextMenuOpen\(\)/)
  assert.match(contextMenuSource, /import \{ clearActiveContextMenu, setActiveContextMenu \} from '\.\/context-menu-registry'/)
  assert.match(contextMenuSource, /onOpenChange=\{handleOpenChange\}/)
  assert.match(contextMenuSource, /ContextMenuPrimitive\.Backdrop/)
  assert.match(contextMenuSource, /data-slot="context-menu-backdrop"/)
  assert.match(contextMenuSource, /fixed inset-0 z-60/)
  assert.match(contextMenuSource, /className="isolate z-70"/)
  assert.match(contextMenuSource, /relative isolate z-70 min-w-40/)
  assert.match(contextMenuSource, /onPointerDown=\{stopBackdropEvent\}/)
  assert.match(contextMenuSource, /onClick=\{stopBackdropEvent\}/)
  assert.match(contextMenuSource, /rounded-xl bg-popover p-1/)
  assert.match(contextMenuSource, /min-h-6 min-w-36/)
  assert.match(contextMenuSource, /gap-1\.5 rounded-lg px-2 py-1 text-\[13px\]/)
  assert.match(inputSource, /@base-ui\/react\/input/)
  assert.match(inputSource, /data-slot="input"/)
  assert.match(inputSource, /focus-visible:border-ring/)
  assert.match(tabsSource, /@base-ui\/react\/tabs/)
  assert.match(tabsSource, /data-slot="tabs"/)
  assert.match(tabsSource, /data-slot="tabs-list"/)
  assert.match(tabsSource, /data-slot="tabs-trigger"/)
  assert.doesNotMatch(tabsSource, /TabsIndicator/)
  assert.match(tooltipSource, /@base-ui\/react\/tooltip/)
  assert.match(tooltipSource, /import \{ isContextMenuOpen \} from '\.\/context-menu-registry'/)
  assert.match(tooltipSource, /data-slot="tooltip-content"/)
  assert.match(tooltipSource, /TOOLTIP_INITIAL_REST_DELAY_MS = 500/)
  assert.match(tooltipSource, /TOOLTIP_ADJACENT_REST_DELAY_MS = 180/)
  assert.match(tooltipSource, /TOOLTIP_ADJACENT_REST_WINDOW_MS = 700/)
  assert.match(tooltipSource, /TOOLTIP_HOVERABLE_CLOSE_DELAY_MS = 160/)
  assert.match(tooltipSource, /TOOLTIP_HOVER_WATCH_INTERVAL_MS = 80/)
  assert.doesNotMatch(tooltipSource, /TooltipPrimitive\.Provider/)
  assert.match(tooltipSource, /disableHoverablePopup = false/)
  assert.match(tooltipSource, /trackCursorAxis = 'none'/)
  assert.match(tooltipSource, /tooltipOpen/)
  assert.match(tooltipSource, /open=\{tooltipOpen\}/)
  assert.match(tooltipSource, /setTooltipOpen\(false\)/)
  assert.match(tooltipSource, /useAbortableEffect\(\(signal\) => \{[\s\S]*window\.addEventListener\('scroll', handleScroll, \{ capture: true, passive: true, signal \}\)/)
  assert.match(tooltipSource, /window\.addEventListener\('blur', handleWindowBlur, \{ signal \}\)/)
  assert.doesNotMatch(tooltipSource, /window\.removeEventListener\('scroll', handleScroll/)
  assert.doesNotMatch(tooltipSource, /window\.removeEventListener\('blur', handleWindowBlur/)
  assert.match(tooltipSource, /foxact\/merge-refs/)
  assert.match(tooltipSource, /foxact\/use-abortable-effect/)
  assert.match(tooltipSource, /foxact\/use-retimer/)
  assert.doesNotMatch(tooltipSource, /foxact\/use-page-visibility/)
  assert.doesNotMatch(tooltipSource, /usePageVisibility/)
  assert.match(tooltipSource, /const handleVisibilityChange = \(\) => \{[\s\S]*document\.visibilityState !== 'visible'[\s\S]*closeTooltip\(\)/)
  assert.match(tooltipSource, /document\.addEventListener\('visibilitychange', handleVisibilityChange, \{ signal \}\)/)
  assert.doesNotMatch(tooltipSource, /document\.removeEventListener\('visibilitychange', handleVisibilityChange/)
  assert.match(tooltipSource, /latestPointerPointRef/)
  assert.match(tooltipSource, /retimeHoverOpen/)
  assert.match(tooltipSource, /retimeHoverClose/)
  assert.match(tooltipSource, /hoverCloseScheduledRef/)
  assert.match(tooltipSource, /onOpenChange\?: \(open: boolean\) => void/)
  assert.match(tooltipSource, /onOpenChange\?\.\(true\)/)
  assert.match(tooltipSource, /onOpenChange\?\.\(false\)/)
  assert.match(tooltipSource, /pointerFocusedRef/)
  assert.match(tooltipSource, /popupPointerInsideRef/)
  assert.match(tooltipSource, /shouldUseAdjacentTooltipDelay/)
  assert.match(tooltipSource, /onPointerEnter=\{handleContentPointerEnter\}/)
  assert.match(tooltipSource, /onPointerLeave=\{handleContentPointerLeave\}/)
  assert.match(tooltipSource, /onMouseEnter=\{handleContentMouseEnter\}/)
  assert.match(tooltipSource, /onMouseLeave=\{handleContentMouseLeave\}/)
  assert.match(tooltipSource, /pointerInsideRef\.current \|\| popupPointerInsideRef\.current/)
  assert.match(tooltipSource, /setTooltipWheelPassthrough/)
  assert.match(tooltipSource, /startTooltipWheelForwarding/)
  assert.match(tooltipSource, /handleTooltipWheelForward/)
  assert.match(tooltipSource, /tooltipWheelForwardRefresh\?\.\(\)/)
  assert.match(tooltipSource, /TOOLTIP_WHEEL_TARGET_RELEASE_DELAY_MS = 320/)
  assert.match(tooltipSource, /data-tooltip-wheel-closing/)
  assert.match(tooltipSource, /window\.addEventListener\('wheel', handleTooltipWheelForward/)
  assert.match(tooltipSource, /target\.style\.setProperty\('pointer-events', 'none'\)/)
  assert.match(tooltipSource, /TOOLTIP_WHEEL_CLOSE_REOPEN_BLOCK_MS = 900/)
  assert.match(tooltipSource, /if \(!hoverCloseScheduledRef\.current\) \{[\s\S]*scheduleHoverClose\(\)/)
  assert.match(tooltipSource, /if \(isContextMenuOpen\(\)\) \{[\s\S]*clearHoverCloseTimer\(\)[\s\S]*return[\s\S]*\}/)
  assert.match(tooltipSource, /matches\(':hover'\)/)
  assert.match(tooltipSource, /window\.addEventListener\('pointermove', handlePointerMove, \{ capture: true, signal \}\)/)
  assert.doesNotMatch(tooltipSource, /document\.addEventListener\('pointermove'/)
  assert.doesNotMatch(tooltipSource, /addEventListener\('mousemove'/)
  assert.match(tooltipSource, /!pointerFocusedRef\.current[\s\S]*triggerElement\?\.contains\(activeElement\)/)
  assert.match(tooltipSource, /const focusVisible = event\.currentTarget\.matches\(':focus-visible'\)/)
  assert.match(tooltipSource, /pointerFocusedRef\.current = !focusVisible/)
  assert.match(tooltipSource, /if \(!focusVisible\) return/)
  assert.match(tooltipSource, /onPointerDown: handlePointerDown/)
  assert.match(tooltipSource, /if \(event\.button !== 0 \|\| event\.ctrlKey\) return/)
  assert.match(tooltipSource, /onPointerLeave: handlePointerLeave/)
  assert.match(tooltipSource, /<TooltipTrigger render=\{trigger\} disabled/)
  assert.match(tooltipSource, /onClick\?\.\(event\)[\s\S]*event\.stopPropagation\(\)/)
  assert.match(tooltipSource, /onPointerDown\?\.\(event\)[\s\S]*event\.stopPropagation\(\)/)
  assert.match(tooltipSource, /TOOLTIP_CLOSE_ANCHOR_CLEAR_DELAY_MS = 200/)
  assert.match(tooltipSource, /retimeFrozenPointerClear/)
  assert.match(tooltipSource, /'children' \| 'content'/)
  assert.match(tooltipSource, /anchorToCursor\?: boolean/)
  assert.match(tooltipSource, /anchorToCursor = true/)
  assert.match(tooltipSource, /new DOMRect\(frozenPointerPoint\.x, frozenPointerPoint\.y, 0, 0\)/)
  assert.match(tooltipSource, /const tooltipAnchor = anchorToCursor \? cursorAnchor : undefined/)
  assert.match(tooltipSource, /positionMethod=\{tooltipAnchor \? 'fixed' : undefined\}/)
  assert.match(tooltipSource, /side = 'bottom'/)
  assert.match(tooltipSource, /align = 'start'/)
  assert.match(tooltipSource, /instant = false/)
  assert.match(tooltipSource, /openInstantly: contentProps\.instant === true/)
  assert.match(tooltipSource, /if \(openInstantly\) \{[\s\S]*openTooltip\(point\)[\s\S]*return[\s\S]*\}/)
  assert.match(tooltipSource, /if \(closeInstantly\) \{[\s\S]*closeTooltip\(\)[\s\S]*return[\s\S]*\}/)
  assert.match(tooltipSource, /document\.elementFromPoint\(point\.x, point\.y\)/)
  assert.match(tooltipSource, /instant\s*\?\s*'transition-none'/)
  assert.match(tooltipSource, /TOOLTIP_EDGE_BORDER_ALIGN_OFFSET_PX = 1/)
  assert.match(tooltipSource, /alignOffset = TOOLTIP_EDGE_BORDER_ALIGN_OFFSET_PX/)
  assert.match(tooltipSource, /sideOffset = 16/)
  assert.match(tooltipSource, /arrowPadding = 0/)
  assert.match(tooltipSource, /collisionPadding = 4/)
  assert.match(tooltipSource, /TOOLTIP_COLLISION_AVOIDANCE/)
  assert.match(tooltipSource, /align: 'flip'/)
  assert.match(tooltipSource, /rounded-\[10px\]/)
  assert.match(tooltipSource, /data-\[align=start\]:data-\[side=bottom\]:rounded-tl-none/)
  assert.match(tooltipSource, /data-\[align=end\]:data-\[side=bottom\]:rounded-tr-none/)
  assert.match(tooltipSource, /\[overflow-wrap:anywhere\]/)
  assert.match(tooltipSource, /bg-\[canvas\]/)
  assert.doesNotMatch(tooltipSource, /TooltipPrimitive\.Arrow/)
  assert.doesNotMatch(tooltipSource, /function ArrowSvg/)
  assert.match(tooltipSource, /TooltipAnchor/)
  assert.match(tooltipSource, /tooltipScrollableAncestors/)
  assert.match(tooltipSource, /tooltipScrollableAncestorsUnderPoint/)
  assert.match(tooltipSource, /document\.elementFromPoint\(x, y\)/)
  assert.match(tooltipSource, /uniqueTooltipScrollableAncestors/)
  assert.match(tooltipSource, /handleContentWheelRef/)
  assert.match(tooltipSource, /popupElement\.addEventListener\('wheel', handleWheel, \{\s*passive: false,\s*signal\s*\}\)/)
  assert.doesNotMatch(tooltipSource, /popupElement\.removeEventListener\('wheel', handleWheel\)/)
  assert.doesNotMatch(tooltipSource, /onWheel=\{handleContentWheel\}/)
  assert.match(pageChipSource, /chipTextTruncationCallbacks/)
  assert.match(pageChipSource, /getBoundingClientRect\(\)\.width/)
  assert.match(pageChipSource, /getBoundingClientRect\(\)\.height/)
  assert.match(pageChipSource, /useId\(\)/)
  assert.match(pageChipSource, /activeExpandedPageChipId/)
  assert.match(pageChipSource, /subscribeToExpandedPageChip/)
  assert.match(pageChipSource, /PAGE_CHIP_EXPANDED_VIEWPORT_MARGIN_PX = 12/)
  assert.doesNotMatch(pageChipSource, /PAGE_CHIP_EXPANDED_MAX_WIDTH_OFFSET_PX/)
  assert.match(pageChipSource, /PAGE_CHIP_EXPANDED_CLOSE_DELAY_MS = 160/)
  assert.match(pageChipSource, /PAGE_CHIP_EXPANDED_WIDTH_GUARD_PX = 8/)
  assert.match(pageChipSource, /PAGE_CHIP_EXPANDED_WIDTH_SEARCH_STEPS = 12/)
  assert.match(pageChipSource, /function getVisibleChipTextLineCount\(textEl: HTMLElement \| null\)/)
  assert.match(pageChipSource, /function getExpandedPageChipLineHtml\(textEl: HTMLElement \| null\)/)
  assert.match(pageChipSource, /function getExpandedPageChipContentWidth\(/)
  assert.match(pageChipSource, /function createExpandedPageChipMeasureElement\(/)
  assert.match(pageChipSource, /page-chip-expansion-measure/)
  assert.match(pageChipSource, /function getPageChipExpansionGeometry\(chipEl: HTMLElement \| null, textEl: HTMLElement \| null = chipEl\?\.querySelector/)
  assert.match(pageChipSource, /const roomToRight = Math\.max\(0, viewportWidth - rect\.left - PAGE_CHIP_EXPANDED_VIEWPORT_MARGIN_PX\)/)
  // The expansion always grows rightward from the chip's left edge so the collapsed
  // text keeps a stable position; never anchor at the right edge / grow left.
  assert.match(pageChipSource, /const maxWidth = Math\.max\(rect\.width, roomToRight\)/)
  assert.match(pageChipSource, /x: 'start'/)
  assert.doesNotMatch(pageChipSource, /roomToLeft/)
  assert.match(pageChipSource, /lineHtml = getExpandedPageChipLineHtml\(textEl\)/)
  assert.match(pageChipSource, /const contentBoxEl = chipEl\.querySelector<HTMLElement>\('\.chip-text'\) \|\| textEl/)
  assert.match(pageChipSource, /function getTitleVariantMinimumContentWidth\(textEl: HTMLElement \| null\)/)
  assert.match(pageChipSource, /Math\.max\(getChipTextExpansionBaselineWidth\(contentBoxEl\), getTitleVariantMinimumContentWidth\(contentBoxEl\)\)/)
  assert.match(pageChipSource, /width: Math\.min\(maxWidth, Math\.max\(rect\.width, minWidth, contentMetrics\.width \+ horizontalInset\)\)/)
  assert.match(pageChipSource, /function roundedElementSize\(element: HTMLElement \| null\)/)
  assert.match(pageChipSource, /const \[chipSlotSize, setChipSlotSize\] = useState\(DEFAULT_CHIP_SLOT_SIZE\)/)
  assert.match(pageChipSource, /const \[chipExpansionGeometry, setChipExpansionGeometry\] = useState\(DEFAULT_CHIP_EXPANSION_GEOMETRY\)/)
  assert.match(pageChipSource, /ResizeObserver\(\(\) => \{[\s\S]*!chipExpandedRef\.current[\s\S]*updateChipSlotMeasurements\(chipEl\)/)
  assert.match(pageChipSource, /pageTargetMatchUrls\(target\)/)
  assert.match(pageChipSource, /pageTargetMatchesHover\(target, activeHoverUrl, activeHoverUrls\)/)
  assert.match(pageChipOverflowSource, /pageTargetMatchesHover\(chip, activeHoverUrl, activeHoverUrls\)/)
  assert.match(pageChipSource, /chip-text-expansion-hit-area -my-\[5px\][\s\S]*py-\[5px\]/)
  assert.match(pageChipSource, /function onChipPointerEnter\(\) \{[\s\S]*openChipExpansion\(\)/)
  assert.match(pageChipSource, /function isPointerInsideChipSlot\(e: PointerEvent<HTMLDivElement>\) \{[\s\S]*chipSlotRef\.current\?\.getBoundingClientRect\(\)/)
  assert.match(pageChipSource, /function onChipPointerMove\(e: PointerEvent<HTMLDivElement>\) \{[\s\S]*chipExpandedRef\.current[\s\S]*isPointerInsideChipSlot\(e\)[\s\S]*openChipExpansion\(\)/)
  assert.match(pageChipSource, /onPointerEnter=\{onChipPointerEnter\}/)
  assert.match(pageChipSource, /onPointerMove=\{onChipPointerMove\}/)
  assert.doesNotMatch(pageChipSource, /onPointerEnter=\{onChipTextExpansionHitAreaPointerEnter\}/)
  assert.match(pageChipSource, /const titleVariantTitleExpansionTriggerElement = \(/)
  assert.match(pageChipSource, /const foldedTitleExpansionTriggerElement = \(/)
  assert.doesNotMatch(pageChipSource, /titleVariantTooltipContentNode/)
  assert.doesNotMatch(pageChipSource, /getChipTooltipAnchor/)
  assert.doesNotMatch(pageChipSource, /chip-text-tooltip-hit-area/)
  assert.match(pageChipSource, /page-chip-tooltip-open/)
  assert.match(pageChipSource, /PAGE_CHIP_SURFACE_INTERACTION_CLASSES = 'hover:bg-\(--chip-interaction-bg\)/)
  assert.match(pageChipSource, /\[\&\.page-chip-tooltip-open\]:bg-\(--chip-interaction-bg\)/)
  assert.match(pageChipSource, /PAGE_CHIP_GROUP_INTERACTION_BG = 'color-mix\(in srgb, var\(--card-bg\) 96\.5%, var\(--color-neutral-600\) 3\.5%\)'/)
  assert.match(pageChipSource, /page-chip-expanded absolute z-30/)
  assert.match(pageChipSource, /page-chip-expanded absolute z-30 min-w-0/)
  assert.match(pageChipSource, /max-w-\(--page-chip-expanded-max-width\)/)
  assert.match(pageChipSource, /!transition-none/)
  assert.match(pageChipSource, /w-\(--page-chip-expanded-width\)/)
  assert.match(pageChipSource, /shadow-\[0_3px_10px_rgba\(10,10,10,0\.055\)\]/)
  assert.match(pageChipSource, /const closeOnPointerMove = \(event: globalThis\.PointerEvent\) =>/)
  assert.match(pageChipSource, /chipSlotRef\.current\?\.getBoundingClientRect\(\)/)
  assert.match(pageChipSource, /window\.addEventListener\('pointermove', closeOnPointerMove, true\)/)
  assert.match(pageChipSource, /window\.removeEventListener\('pointermove', closeOnPointerMove, true\)/)
  assert.match(pageChipSource, /'--page-chip-expanded-width': chipExpandedWidth/)
  assert.match(pageChipSource, /const chipInteractionBg = isCurrentActiveFrame/)
  assert.match(pageChipSource, /PAGE_CHIP_CLICKABLE_INTERACTION_BG = 'color-mix\(in srgb, var\(--card-bg\) 90%, var\(--color-neutral-600\) 10%\)'/)
  assert.match(pageChipSource, /PAGE_CHIP_ACTIVE_OTHER_INTERACTION_BG = 'color-mix\(in srgb, var\(--card-bg\) 88%, var\(--color-neutral-600\) 12%\)'/)
  assert.doesNotMatch(pageChipSource, /backgroundColor: 'var\(--chip-hover-fade-bg\)'/)
  assert.match(pageChipSource, /width: chipExpandedWidth/)
  assert.match(pageChipSource, /page-chip-expanded-line/)
  assert.match(pageChipSource, /chipExpansionLineNodesFromHtml/)
  assert.match(pageChipSource, /data-expanded=\{chipExpanded \? 'true' : undefined\}/)
  assert.match(pageChipSource, /data-tabout-part="slot"/)
  assert.match(pageChipSource, /chip-slot relative min-w-0/)
  assert.match(pageChipSource, /PAGE_CHIP_TOOLTIP_SUPPRESSION_MARKER_CLASS_NAME/)
  assert.doesNotMatch(pageChipSource, /hover:bg-\[rgba\(10,10,10,0\.12\)\]/)
  assert.doesNotMatch(pageChipSource, /\[\&\.page-chip-context-menu-open\]:bg-\[rgba\(10,10,10,0\.12\)\]/)
  assert.match(pageChipSource, /group-\[\.page-chip-expanded\]\/page-chip:hidden/)
  assert.match(pageChipSource, /group-\[\.page-chip-expanded\]\/page-chip:inline/)
  assert.match(pageChipSource, /whitespace-nowrap/)
  assert.doesNotMatch(pageChipSource, /page-chip-tooltip-measure/)
  assert.doesNotMatch(pageChipSource, /page-chip-tooltip-line/)
  assert.doesNotMatch(pageChipSource, /dangerouslySetInnerHTML/)
  assert.match(pageChipSource, /chipTextContentNode\(mode: ChipTextRenderMode\)/)
  assert.match(pageChipSource, /chipTextContentNode\('tooltip'\)/)
  assert.match(pageChipSource, /chipTextContentNode\('chip'\)/)
  assert.match(pageChipSource, /page-chip-tooltip max-w-\[calc\(100vw-16px\)\] text-\[13px\] leading-tight wrap-break-word/)
  assert.match(pageChipSource, /hyphens-auto break-normal/)
  assert.match(pageChipSource, /inline-block max-w-\[calc\(100%-6px\)\] whitespace-normal break-normal w-max wrap-break-word/)
  assert.doesNotMatch(pageChipSource, /duplicateLabel \|\| activeLabel/)
  assert.doesNotMatch(pageChipSource, /\? chip\.tooltip : undefined/)
  assert.doesNotMatch(pageChipSource, /@chenglou\/pretext/)
  assert.match(tabHistoryPanelSource, /historyTitleTruncationCallbacks/)
  assert.match(tabHistoryPanelSource, /HISTORY_ENTRY_EXPANDED_VIEWPORT_MARGIN_PX = 12/)
  assert.match(tabHistoryPanelSource, /HISTORY_ENTRY_EXPANDED_CLOSE_DELAY_MS = 160/)
  assert.match(tabHistoryPanelSource, /HISTORY_ENTRY_EXPANDED_WIDTH_GUARD_PX = 8/)
  assert.match(tabHistoryPanelSource, /useState<HistoryTitleMetrics>/)
  assert.match(tabHistoryPanelSource, /titleEl\.scrollHeight - titleEl\.clientHeight > 1/)
  assert.match(tabHistoryPanelSource, /getHistoryTitleContentWidth/)
  assert.match(tabHistoryPanelSource, /getHistoryTitleExpandedLineHtml/)
  assert.match(tabHistoryPanelSource, /historyTitleExpandedLineMarkup/)
  assert.match(tabHistoryPanelSource, /historyTitleExpandedLineNodesFromHtml/)
  assert.match(tabHistoryPanelSource, /expandedViewportConstrained/)
  assert.match(tabHistoryPanelSource, /visibleLineCount/)
  assert.match(tabHistoryPanelSource, /getBoundingClientRect\(\)\.width/)
  assert.match(tabHistoryPanelSource, /activeExpandedHistoryEntryId/)
  assert.match(tabHistoryPanelSource, /subscribeToExpandedHistoryEntry/)
  assert.match(tabHistoryPanelSource, /function getHistoryTitleExpandedTextWidth\(/)
  assert.match(tabHistoryPanelSource, /history-entry-title-expansion-measure/)
  assert.match(tabHistoryPanelSource, /--history-entry-expanded-width/)
  assert.match(tabHistoryPanelSource, /const \[titleExpanded, setTitleExpandedState\] = useState\(false\)/)
  assert.match(tabHistoryPanelSource, /titleExpanded && 'history-entry-expanded-open'/)
  assert.match(tabHistoryPanelSource, /titleExpanded && 'history-entry-row-expanded-open'/)
  assert.match(tabHistoryPanelSource, /history-entry-low-score-content opacity-60 group-hover\/history-row:opacity-100 group-focus-within\/history-row:opacity-100 group-\[\.history-entry-row-expanded-open\]\/history-row:opacity-100/)
  assert.doesNotMatch(tabHistoryPanelSource, /dimmed && 'opacity-60 hover:opacity-100 focus-within:opacity-100 \[\&\.history-entry-row-expanded-open\]:opacity-100'/)
  assert.match(tabHistoryPanelSource, /group-\[\.history-entry-row-expanded-open\]\/history-row:text-\[rgba\(115,115,115,0\.54\)\]/)
  assert.match(tabHistoryPanelSource, /function openTitleExpansion\(\)/)
  assert.match(tabHistoryPanelSource, /function closeTitleExpansion\(\{ delayed = true \} = \{\}\)/)
  assert.match(tabHistoryPanelSource, /function onHistoryEntryPointerEnter\(\) \{[\s\S]*openTitleExpansion\(\)/)
  assert.match(tabHistoryPanelSource, /function onHistoryEntryPointerMove\(e: PointerEvent<HTMLDivElement>\)/)
  assert.match(tabHistoryPanelSource, /window\.addEventListener\('pointermove', closeOnPointerMove, true\)/)
  assert.match(tabHistoryPanelSource, /history-entry-title-expansion-hit-area/)
  assert.match(tabHistoryPanelSource, /pageTargetMatchesHover\(entry, activeHoverUrl, activeHoverUrls\)/)
  assert.match(tabHistoryPanelSource, /HISTORY_ENTRY_CLICKABLE_INTERACTION_BG = 'color-mix\(in srgb, var\(--card-bg\) 90%, var\(--color-neutral-600\) 10%\)'/)
  assert.match(tabHistoryPanelSource, /HISTORY_ENTRY_INTERACTION_CLASSES = 'group-hover\/history-row:bg-\(--history-entry-interaction-bg\)[\s\S]*\[\&\.history-entry-expanded-open\]:bg-\(--history-entry-interaction-bg\)/)
  assert.match(tabHistoryPanelSource, /HISTORY_ENTRY_ACTIVE_OTHER_INTERACTION_CLASSES = `bg-\(--history-entry-rest-bg\)/)
  assert.match(tabHistoryPanelSource, /history-entry-expanded-line-tail/)
  assert.match(tabHistoryPanelSource, /data-expanded=\{titleExpanded \? 'true' : undefined\}/)
  assert.match(tabHistoryPanelSource, /function getHistoryEntryExpansionGeometry\(entryEl: HTMLElement \| null, titleEl: HTMLElement \| null\)/)
  assert.match(tabHistoryPanelSource, /const expandedEntryElement = titleExpanded \? historyEntrySurface\(true\) : null/)
  assert.match(tabHistoryPanelSource, /history-entry-list pointer-events-none relative z-10 flex min-h-0[^"]*\[scrollbar-width:none\][^"]*\[\&::-webkit-scrollbar\]:w-0[^"]*max-\[900px\]:w-auto[^"]*max-\[900px\]:mr-\[calc\(var\(--dashboard-edge-bleed\)-var\(--dashboard-scrollbar-inset\)\)\]/)
  assert.match(tabHistoryPanelSource, /history-entry-list-content pointer-events-auto flex self-start w-\[260px\][^"]*pb-10[^"]*max-\[900px\]:pr-0[^"]*max-\[900px\]:pb-3/)
  assert.match(tabHistoryPanelSource, /history-entry-scrollbar pointer-events-none absolute top-0 right-0 bottom-0 z-20/)
  assert.match(tabHistoryPanelSource, /history-entry-scrollbar-track pointer-events-auto absolute/)
  assert.match(tabHistoryPanelSource, /onPointerDown=\{onTrackPointerDown\}/)
  assert.match(tabHistoryPanelSource, /history-entry-scrollbar-thumb absolute top-0 right-0 w-full cursor-grab/)
  assert.match(tabHistoryPanelSource, /onPointerDown=\{onThumbPointerDown\}/)
  assert.match(tabHistoryPanelSource, /--history-entry-scrollbar-thumb-height/)
  assert.match(tabHistoryPanelSource, /className="history-entry-slot relative min-w-0 flex-auto"[\s\S]*\{historyEntrySurface\(false\)\}[\s\S]*\{expandedEntryElement\}/)
  // The expansion no longer collapses on scroll; it stays open until the pointer
  // leaves the entry's slot (or window blur / tab hidden).
  assert.doesNotMatch(tabHistoryPanelSource, /closeExpandedHistoryEntryBeforeNativeScroll/)
  assert.doesNotMatch(tabHistoryPanelSource, /closeExpandedHistoryEntryOnNativeScroll/)
  assert.doesNotMatch(tabHistoryPanelSource, /onWheelCapture=/)
  assert.doesNotMatch(tabHistoryPanelSource, /onScrollCapture=/)
  assert.doesNotMatch(tabHistoryPanelSource, /window\.addEventListener\('scroll'/)
  assert.doesNotMatch(tabHistoryPanelSource, /function getHistoryEntryLayerRoot/)
  assert.doesNotMatch(tabHistoryPanelSource, /layerElement\?: HTMLElement \| null/)
  assert.doesNotMatch(tabHistoryPanelSource, /const \[historyPanelElement, setHistoryPanelElement\]/)
  assert.doesNotMatch(tabHistoryPanelSource, /createPortal/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry-overlay/)
  assert.doesNotMatch(tabHistoryPanelSource, /onHistoryEntryWheel/)
  assert.doesNotMatch(tabHistoryPanelSource, /historyWheelGestureActive/)
  assert.doesNotMatch(tabHistoryPanelSource, /onWheel=\{/)
  assert.doesNotMatch(tabHistoryPanelSource, /scrollTop\s*=/)
  assert.match(tabHistoryPanelSource, /history-entry-expanded pointer-events-none absolute left-0 z-30/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry-expanded pointer-events-auto/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry-expanded fixed z-30/)
  assert.match(tabHistoryPanelSource, /shadow-\[0_3px_10px_rgba\(10,10,10,0\.055\)\]/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry-title-expansion line-clamp-2/)
  assert.match(tabHistoryPanelSource, /w-\(--history-entry-expanded-title-width\)/)
  assert.doesNotMatch(tabHistoryPanelSource, /\[text-wrap:balance\]/)
  assert.doesNotMatch(tabHistoryPanelSource, /w-max/)
  assert.doesNotMatch(tabHistoryPanelSource, /TooltipAnchor/)
  assert.doesNotMatch(tabHistoryPanelSource, /getHistoryTitleTooltipAnchor/)
  assert.doesNotMatch(tabHistoryPanelSource, /anchorToCursor=\{false\}/)
  assert.doesNotMatch(tabHistoryPanelSource, /sideOffset=\{0\}/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry-title-tooltip/)
  assert.match(tabHistoryPanelSource, /wrap-break-word/)
  assert.match(tabHistoryPanelSource, /\[font-family:inherit\]/)
  assert.match(tabHistoryPanelSource, /focus-within:shadow-\[inset_0_0_0_1px_rgba\(234,179,8,0\.42\)\]/)
  assert.match(tabHistoryPanelSource, /history-entry group\/history-entry[^"]*rounded-\[10px\][^"]*border-0[^"]*bg-transparent/)
  assert.match(tabHistoryPanelSource, /history-entry-title block min-w-0 flex-auto overflow-hidden hyphens-auto break-normal max-h-\[calc\(2lh\)\]/)
  assert.match(tabHistoryPanelSource, /\[\&\.history-entry-title-truncated\]:\[mask-image:linear-gradient\(to_bottom,black_0,black_calc\(100%_-_1lh\),transparent_calc\(100%_-_1lh\)\),linear-gradient\(to_right,black_0,black_calc\(100%_-_60px\),rgba\(0,0,0,0\.35\)_calc\(100%_-_20px\),transparent\)\]/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry-title line-clamp-2/)
  assert.match(tabHistoryPanelSource, /group-hover\/history-row:bg-\(--history-entry-interaction-bg\)/)
  assert.doesNotMatch(tabHistoryPanelSource, /border border-\(--warm-gray\)/)
  assert.doesNotMatch(tabHistoryPanelSource, /group-hover\/history-row:border-\(--accent-amber\)/)
  assert.match(tabHistoryPanelSource, /after:w-0/)
  assert.doesNotMatch(tabHistoryPanelSource, /after:w-14/)
  assert.match(tabHistoryPanelSource, /className="history-entry-main flex min-h-8\.5[^"]*cursor-default[^"]*items-start[^"]*focus-visible:outline-none/)
  assert.match(tabHistoryPanelSource, /className="history-entry-close history-entry-close-favicon pointer-events-none absolute[^"]*group-hover\/history-favicon-frame:pointer-events-auto[^"]*focus-visible:outline-2/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry group\/history-entry[^"]*\btransition-/)
  assert.doesNotMatch(tabHistoryPanelSource, /className="history-entry-close history-entry-close-favicon[^"]*\btransition-/)
  assert.doesNotMatch(tabHistoryPanelSource, /<TooltipAnchor/)
  assert.match(pathgroupSectionSource, /pathgroupLabelTruncated \? \(/)
  assert.match(pathgroupSectionSource, /className="text-\[13px\] leading-tight"/)
  assert.doesNotMatch(pathgroupSectionSource, /<TooltipAnchor content=\{displayLabel\}>/)
  assert.match(tooltipSource, /mergeRefs<HTMLElement>\(children\.props\.ref, triggerElementRef\)/)
  assert.match(tooltipSource, /children\.props\.ref/)
  assert.match(selectSource, /@base-ui\/react\/select/)
  assert.match(selectSource, /lucide-react/)
  assert.match(selectSource, /@\/lib\/utils/)
  assert.match(utilsSource, /import \{ clsx, type ClassValue \} from 'clsx'/)
  assert.match(utilsSource, /import \{ twMerge \} from 'tailwind-merge'/)
  assert.match(utilsSource, /export function cn/)
  assert.equal(existsSync('src/lib/cn.ts'), false)
  assert.match(appStylesheet, /--color-input:/)
  assert.match(appStylesheet, /--color-popover:/)
  assert.match(appStylesheet, /--color-popover-foreground:/)
  assert.match(appStylesheet, /--color-ring:/)
  assert.match(selectSource, /data-slot="select-trigger"/)
  assert.match(selectSource, /data-size=\{size\}/)
  assert.match(selectSource, /border-input bg-transparent py-2 pr-2 pl-2\.5 text-sm whitespace-nowrap transition-colors/)
  assert.match(selectSource, /data-placeholder:text-muted-foreground/)
  assert.match(selectSource, /data-slot="select-content"/)
  assert.match(selectSource, /max-h-\(--available-height\) w-\(--anchor-width\) min-w-36/)
  assert.match(selectSource, /SelectPrimitive\.ScrollUpArrow/)
  assert.match(selectSource, /SelectPrimitive\.ScrollDownArrow/)
  assert.match(selectSource, /SelectPrimitive\.ItemIndicator/)
  assert.match(selectSource, /SelectPrimitive\.ItemText className="flex flex-1 shrink-0 gap-2 whitespace-nowrap"/)
  assert.match(selectSource, /pointer-events-none absolute right-2 flex size-4 items-center justify-center/)
  assert.match(selectSource, /ChevronDownIcon/)
  assert.match(selectSource, /ChevronUpIcon/)
  assert.match(selectSource, /data-slot="select-scroll-up-button"/)
  assert.match(selectSource, /data-slot="select-scroll-down-button"/)
  assert.match(selectSource, /align = 'center'/)
  assert.match(selectSource, /alignItemWithTrigger = true/)
  assert.match(selectSource, /data-align-trigger/)
  assert.doesNotMatch(headerBarSource, /from '\.\/ui\/button'/)
  assert.match(headerBarSource, /from '\.\/ui\/input'/)
  assert.match(headerBarSource, /from '\.\/ui\/select'/)
  assert.match(headerBarSource, /from '\.\/ui\/tabs'/)
  assert.match(headerBarSource, /function HistoryRangeSelect/)
  assert.match(headerBarSource, /<Select value=\{value\} items=\{HISTORY_RANGE_OPTIONS\} onValueChange=\{handleValueChange\}>/)
  assert.match(headerBarSource, /<SelectContent[\s\S]*align="start"[\s\S]*alignItemWithTrigger=\{false\}/)
  assert.match(headerBarSource, /<SelectGroup>/)
  assert.match(headerBarSource, /<SelectItem[\s\S]*key=\{option\.value\}[\s\S]*value=\{option\.value\}[\s\S]*label=\{option\.label\}/)
  assert.doesNotMatch(headerBarSource, /SelectControl|TextInput|SegmentedTabs/)
  assert.deepEqual(uiFiles, ['button-variants.ts', 'button.tsx', 'context-menu-registry.ts', 'context-menu.tsx', 'input.tsx', 'select.tsx', 'tabs-variants.ts', 'tabs.tsx', 'tooltip.tsx'])
  assert.match(toastSource, /p-4!/)
  assert.match(toastSource, /mt-2!/)
  assert.match(toastSource, /px-3!/)
  assert.match(toastSource, /fixed bottom-4 left-4 right-auto top-auto/)
  assert.match(toastSource, /min-\[500px\]:left-8/)
  assert.match(toastSource, /origin-\[bottom_center\]/)
  assert.doesNotMatch(toastSource, /origin-\[bottom_left\]/)
  assert.doesNotMatch(toastSource, /min-\[500px\]:right-8/)
  assert.match(toastSource, /rounded-3xl \[corner-shape:squircle\]/)
  assert.match(toastSource, /<BaseToast\.Content className="[^"]*data-behind:opacity-0/)
  assert.match(toastSource, /rounded-xl \[corner-shape:squircle\]/)
  assert.match(toastSource, /rounded-full border-0 bg-transparent/)
  assert.match(toastSource, /<XIcon className="size-3" \/>/)
  assert.match(toastSource, /\[corner-shape:squircle\]/)
  assert.doesNotMatch(toastSource, /rounded-sm/)
  assert.match(baseStylesheet, /button,\ninput,\nselect,\ntextarea\s*\{\n\s*font-family: inherit;/)
  assert.match(appComponentSource, /'scroll-region[^']*overflow-x-hidden[^']*overflow-y-auto[^']*overscroll-y-contain[^']*'/)
  assert.match(baseStylesheet, /--dashboard-scrollbar-size: 10px;/)
  assert.match(baseStylesheet, /--dashboard-scrollbar-thumb-bg: rgba\(0, 0, 0, 0\.44\);/)
  assert.match(appComponentSource, /'scroll-region[^']*\[scrollbar-color:var\(--dashboard-scrollbar-thumb-bg\)_transparent\][^']*\[scrollbar-width:auto\]/)
  assert.match(baseStylesheet, /\.scroll-region::-webkit-scrollbar\s*\{[\s\S]*width: var\(--dashboard-scrollbar-size\);/)
  assert.match(baseStylesheet, /\.scroll-region::-webkit-scrollbar-thumb\s*\{[\s\S]*min-height: 33px;[\s\S]*border: var\(--dashboard-scrollbar-padding\) solid transparent;[\s\S]*background: var\(--dashboard-scrollbar-thumb-bg\);/)
  assert.match(pageChipSource, /'chip-dupe-badge [^']*items-start[^']*px-0[^']*pt-px/)
  assert.match(pageChipSource, /dupeCount > 9 && 'chip-dupe-badge-wide [^']*px-1/)
  assert.match(pageChipSource, /dedupeBadgesClosing && 'closing'/)
  assert.match(domainCardContextSource, /createContext\(defaultDomainCardContext\)/)
  assert.match(domainCardSource, /<DomainCardProvider value=\{cardContext\}>/)
  assert.match(useHoverMatchSource, /const \[hoverMatch, setHoverMatch\] = useState/)
  assert.match(useHoverMatchSource, /useState<HoverMatchState>\(\{ url: '', urls: \[\], source: null \}\)/)
  assert.match(useHoverMatchSource, /function sameHoverUrls/)
  assert.match(useHoverMatchSource, /function handleHoverUrlChange\(url: string, source: HoverUrlSource = 'chip', matchUrls\?: readonly string\[\]\)/)
  assert.match(useHoverMatchSource, /setHoverMatch/)
  assert.match(useHoverMatchSource, /setUrlPreview\(nextUrl\)/)
  assert.match(appComponentSource, /activeHoverUrl=\{hoverMatch\.url\}/)
  assert.match(appComponentSource, /activeHoverUrls=\{hoverMatch\.urls\}/)
  assert.match(appComponentSource, /activeHoverSource=\{hoverMatch\.source\}/)
  assert.match(`${flatSectionSource}\n${pageChipSource}\n${pathgroupSectionSource}\n${subdomainSectionSource}`, /useDomainCardContext/)
  assert.doesNotMatch(`${flatSectionSource}\n${pathgroupSectionSource}\n${subdomainSectionSource}`, /dedupeBadgesClosing\?:|onActiveSuppressedTitleChange\?:|onHoverUrlChange\?:|onLayoutChange\?:/)
  assert.doesNotMatch(domainCardSource, /querySelectorAll/)
  assert.doesNotMatch(`${appSource}\n${appComponentSource}\n${toastSource}`, /vendor\/preact|vendor\/htm/)
  assert.doesNotMatch(sharedTypesSource, /const chrome:\s*any/)
  assert.doesNotMatch(sharedTypesSource, /LOCAL_PATH_GROUPERS\?:\s*any\[\]/)
})

test('repo pre-commit hook runs the verification pipeline', () => {
  assert.ok(existsSync('.githooks/pre-commit'), 'pre-commit hook should be committed for local setup')

  const hook = readFileSync('.githooks/pre-commit', 'utf8')
  assert.match(hook, /^#!\/bin\/sh/)
  assert.match(hook, /pnpm verify/)
})

test('built extension bundle is packaged locally', () => {
  assert.ok(existsSync('extension/dist/app.js'), 'extension/dist/app.js should be committed build output for unpacked extension loading')
  assert.ok(existsSync('extension/dist/background.js'), 'extension/dist/background.js should be committed service worker output')
  assert.equal(existsSync('extension/dist/app.js.map'), false, 'production build should not ship a sourcemap')
  assert.equal(existsSync('extension/dist/background.js.map'), false, 'production build should not ship a service-worker sourcemap')
  assert.equal(existsSync('extension/dist/chunks'), false, 'dashboard UI should be bundled into one JS entry')
  assert.ok(existsSync('extension/dist/assets/app.css'), 'extension/dist/assets/app.css should be committed stylesheet output')

  const distFiles = readdirSync('extension/dist').sort()
  assert.deepEqual(distFiles, ['app.js', 'assets', 'background.js'])
  assert.deepEqual(readdirSync('extension/dist/assets').sort(), ['app.css'])
  assert.deepEqual(readdirSync('extension').filter((name) => name.endsWith('.js')), ['config.local.js'])

  const bundle = readFileSync('extension/dist/app.js', 'utf8')
  const backgroundBundle = readFileSync('extension/dist/background.js', 'utf8')
  const stylesheet = readFileSync('extension/dist/assets/app.css', 'utf8')
  assert.doesNotMatch(bundle, /from\s+['"]https?:\/\//)
  assert.doesNotMatch(backgroundBundle, /from\s+['"]https?:\/\//)
  assert.doesNotMatch(bundle, /vendor\/preact|vendor\/htm/)
  assert.match(bundle, /mission-card/)
  assert.match(stylesheet, /\.dashboard-main/)
  assert.match(stylesheet, /body\{[^}]*font-family:sans-serif/)
  assert.doesNotMatch(stylesheet, /@layer base\{/)
  assert.doesNotMatch(stylesheet, /@layer components\{/)
  assert.doesNotMatch(stylesheet, /@font-face/)
  assert.doesNotMatch(stylesheet, /url\(["']?https?:\/\//)
  assert.doesNotMatch(stylesheet, /tailwindcss\/preflight/)
})
