import assert from 'node:assert/strict'
import test from 'node:test'
import { existsSync, readdirSync, readFileSync } from 'node:fs'

test('extension HTML loads the Vite-built React entry', () => {
  assert.ok(existsSync('package.json'), 'package.json should define the Vite build')
  assert.ok(existsSync('scripts/watch-build.mjs'), 'scripts/watch-build.mjs should drive local rebuilds without watching dist output')
  assert.ok(existsSync('src/app.tsx'), 'src/app.tsx should be the React entry source')
  assert.ok(existsSync('src/extension/background.ts'), 'src/extension/background.ts should be the service worker source')
  assert.ok(existsSync('components.json'), 'components.json should define the shadcn project setup')

  const pkg = JSON.parse(readFileSync('package.json', 'utf8'))
  const tsconfig = JSON.parse(readFileSync('tsconfig.json', 'utf8'))
  const shadcnConfig = JSON.parse(readFileSync('components.json', 'utf8'))
  assert.match(pkg.packageManager, /^pnpm@/)
  assert.equal(pkg.scripts?.['setup:hooks'], 'git config core.hooksPath .githooks')
  assert.equal(pkg.scripts?.dev, 'node scripts/watch-build.mjs')
  assert.equal(pkg.scripts?.build, 'vite build')
  assert.equal(pkg.scripts?.['build:debug'], 'vite build --sourcemap')
  assert.equal(pkg.scripts?.lint, 'eslint . --max-warnings=0')
  assert.equal(pkg.scripts?.['deps:nolyfill'], 'pnpm dlx nolyfill --pm pnpm')
  assert.match(pkg.scripts?.['test:browser'], /RUN_BROWSER_SMOKE=1/)
  assert.equal(pkg.scripts?.['verify:bundle'], 'git diff --exit-code -- extension/dist')
  assert.match(pkg.scripts?.verify, /pnpm lint/)
  assert.match(pkg.scripts?.verify, /pnpm verify:bundle/)
  assert.match(pkg.scripts?.['verify:browser'], /pnpm test:browser/)
  assert.ok(pkg.dependencies?.react)
  assert.ok(pkg.dependencies?.['react-dom'])
  assert.ok(pkg.dependencies?.['@base-ui/react'])
  assert.ok(pkg.dependencies?.['class-variance-authority'])
  assert.ok(pkg.devDependencies?.['@types/chrome'])
  assert.ok(pkg.devDependencies?.['@rolldown/plugin-babel'])
  assert.ok(pkg.devDependencies?.['@tailwindcss/vite'])
  assert.ok(pkg.devDependencies?.['babel-plugin-react-compiler'])
  assert.ok(pkg.devDependencies?.tailwindcss)
  assert.ok(pkg.devDependencies?.vite)
  assert.ok(pkg.devDependencies?.shadcn)
  assert.ok(tsconfig.compilerOptions?.types?.includes('chrome'))
  assert.equal(tsconfig.compilerOptions?.allowJs, false)
  assert.equal(tsconfig.compilerOptions?.noImplicitAny, true)
  assert.equal(tsconfig.compilerOptions?.strictNullChecks, true)
  assert.deepEqual(tsconfig.compilerOptions?.paths?.['@/*'], ['./src/*'])
  assert.equal(shadcnConfig.style, 'base-nova')
  assert.equal(shadcnConfig.rsc, false)
  assert.equal(shadcnConfig.tsx, true)
  assert.equal(shadcnConfig.tailwind?.css, 'src/styles/app.css')
  assert.equal(shadcnConfig.tailwind?.config, '')
  assert.equal(shadcnConfig.tailwind?.cssVariables, true)
  assert.equal(shadcnConfig.aliases?.ui, '@/components/ui')
  assert.equal(shadcnConfig.aliases?.components, '@/components')
  assert.equal(shadcnConfig.aliases?.utils, '@/lib/utils')
  assert.equal(shadcnConfig.aliases?.lib, '@/lib')

  const indexHtml = readFileSync('extension/index.html', 'utf8')
  assert.match(indexHtml, /href="dist\/assets\/app\.css"/)
  assert.match(indexHtml, /src="dist\/app\.js"/)
  assert.doesNotMatch(indexHtml, /src="app\.js"/)

  const manifest = JSON.parse(readFileSync('extension/manifest.json', 'utf8'))
  assert.equal(manifest.background?.service_worker, 'dist/background.js')

  const viteConfig = readFileSync('vite.config.ts', 'utf8')
  const watchScript = readFileSync('scripts/watch-build.mjs', 'utf8')
  assert.match(viteConfig, /reactCompilerPreset/)
  assert.match(viteConfig, /@rolldown\/plugin-babel/)
  assert.match(viteConfig, /@tailwindcss\/vite/)
  assert.match(viteConfig, /alias:\s*\{\n\s+'@': resolve\(__dirname, 'src'\)/)
  assert.match(viteConfig, /src\/extension\/background\.ts/)
  assert.match(watchScript, /WATCH_TARGETS/)
  assert.match(watchScript, /POLL_MS/)
  assert.doesNotMatch(watchScript, /extension\/dist/)
  assert.doesNotMatch(watchScript, /\bwatch\(/)

  const appSource = readFileSync('src/app.tsx', 'utf8')
  const appStylesheet = readFileSync('src/styles/app.css', 'utf8')
  const appComponentSource = readFileSync('src/components/App.tsx', 'utf8')
  const baseStylesheet = readFileSync('extension/base.css', 'utf8')
  const domainCardSource = readFileSync('src/components/DomainCard.tsx', 'utf8')
  const pageChipSource = readFileSync('src/components/PageChip.tsx', 'utf8')
  const tabHistoryPanelSource = readFileSync('src/components/TabHistoryPanel.tsx', 'utf8')
  const headerBarSource = readFileSync('src/components/HeaderBar.tsx', 'utf8')
  const toastSource = readFileSync('src/components/Toast.tsx', 'utf8')
  const buttonSource = readFileSync('src/components/ui/button.tsx', 'utf8')
  const inputSource = readFileSync('src/components/ui/input.tsx', 'utf8')
  const tabsSource = readFileSync('src/components/ui/tabs.tsx', 'utf8')
  const uiFiles = readdirSync('src/components/ui').sort()
  const selectSource = readFileSync('src/components/ui/select.tsx', 'utf8')
  const tooltipSource = readFileSync('src/components/ui/tooltip.tsx', 'utf8')
  const utilsSource = readFileSync('src/lib/utils.ts', 'utf8')
  const sharedTypesSource = readFileSync('src/extension/types.d.ts', 'utf8')
  assert.match(appSource, /styles\/app\.css/)
  assert.doesNotMatch(
    [appComponentSource, domainCardSource, pageChipSource, tabHistoryPanelSource].join('\n'),
    /text-\[11px\]/
  )
  assert.match(`${appComponentSource}\n${toastSource}`, /react-dom\/client/)
  assert.match(buttonSource, /@base-ui\/react\/button/)
  assert.match(buttonSource, /class-variance-authority/)
  assert.match(buttonSource, /data-slot="button"/)
  assert.match(buttonSource, /buttonVariants/)
  assert.match(buttonSource, /variant:\s*'default'/)
  assert.doesNotMatch(buttonSource, /unstyled: ''/)
  assert.doesNotMatch(buttonSource, /type = 'button'/)
  assert.match(inputSource, /@base-ui\/react\/input/)
  assert.match(inputSource, /data-slot="input"/)
  assert.match(inputSource, /focus-visible:border-ring/)
  assert.match(tabsSource, /@base-ui\/react\/tabs/)
  assert.match(tabsSource, /data-slot="tabs"/)
  assert.match(tabsSource, /data-slot="tabs-list"/)
  assert.match(tabsSource, /data-slot="tabs-trigger"/)
  assert.doesNotMatch(tabsSource, /TabsIndicator/)
  assert.match(tooltipSource, /@base-ui\/react\/tooltip/)
  assert.match(tooltipSource, /data-slot="tooltip-content"/)
  assert.match(tooltipSource, /TOOLTIP_INITIAL_REST_DELAY_MS = 500/)
  assert.match(tooltipSource, /TOOLTIP_ADJACENT_REST_DELAY_MS = 180/)
  assert.match(tooltipSource, /TOOLTIP_ADJACENT_REST_WINDOW_MS = 700/)
  assert.match(tooltipSource, /TOOLTIP_HOVERABLE_CLOSE_DELAY_MS = 160/)
  assert.match(tooltipSource, /TOOLTIP_HOVER_WATCH_INTERVAL_MS = 80/)
  assert.doesNotMatch(tooltipSource, /TooltipPrimitive\.Provider/)
  assert.match(tooltipSource, /disableHoverablePopup = false/)
  assert.match(tooltipSource, /trackCursorAxis = 'none'/)
  assert.match(tooltipSource, /tooltipOpen/)
  assert.match(tooltipSource, /open=\{tooltipOpen\}/)
  assert.match(tooltipSource, /setTooltipOpen\(false\)/)
  assert.match(tooltipSource, /window\.addEventListener\('scroll', handleScroll, true\)/)
  assert.match(tooltipSource, /window\.removeEventListener\('scroll', handleScroll, true\)/)
  assert.match(tooltipSource, /latestPointerPointRef/)
  assert.match(tooltipSource, /hoverOpenTimerRef/)
  assert.match(tooltipSource, /hoverCloseTimerRef/)
  assert.match(tooltipSource, /popupPointerInsideRef/)
  assert.match(tooltipSource, /shouldUseAdjacentTooltipDelay/)
  assert.match(tooltipSource, /onPointerEnter=\{handleContentPointerEnter\}/)
  assert.match(tooltipSource, /onPointerLeave=\{handleContentPointerLeave\}/)
  assert.match(tooltipSource, /onMouseEnter=\{handleContentMouseEnter\}/)
  assert.match(tooltipSource, /onMouseLeave=\{handleContentMouseLeave\}/)
  assert.match(tooltipSource, /pointerInsideRef\.current \|\| popupPointerInsideRef\.current/)
  assert.match(tooltipSource, /matches\(':hover'\)/)
  assert.match(tooltipSource, /document\.addEventListener\('mousemove', handlePointerOrMouseMove, true\)/)
  assert.match(tooltipSource, /onPointerLeave: handlePointerLeave/)
  assert.match(tooltipSource, /<TooltipTrigger render=\{trigger\} disabled/)
  assert.match(tooltipSource, /onClick\?\.\(event\)[\s\S]*event\.stopPropagation\(\)/)
  assert.match(tooltipSource, /onPointerDown\?\.\(event\)[\s\S]*event\.stopPropagation\(\)/)
  assert.match(tooltipSource, /TOOLTIP_CLOSE_ANCHOR_CLEAR_DELAY_MS = 200/)
  assert.match(tooltipSource, /frozenPointerClearTimerRef/)
  assert.match(tooltipSource, /'children' \| 'content'/)
  assert.match(tooltipSource, /new DOMRect\(frozenPointerPoint\.x, frozenPointerPoint\.y, 0, 0\)/)
  assert.match(tooltipSource, /positionMethod=\{cursorAnchor \? 'fixed' : undefined\}/)
  assert.match(tooltipSource, /side = 'bottom'/)
  assert.match(tooltipSource, /align = 'start'/)
  assert.match(tooltipSource, /TOOLTIP_EDGE_BORDER_ALIGN_OFFSET_PX = 1/)
  assert.match(tooltipSource, /alignOffset = TOOLTIP_EDGE_BORDER_ALIGN_OFFSET_PX/)
  assert.match(tooltipSource, /sideOffset = 10/)
  assert.match(tooltipSource, /arrowPadding = 0/)
  assert.match(tooltipSource, /collisionPadding = 0/)
  assert.match(tooltipSource, /TOOLTIP_COLLISION_AVOIDANCE/)
  assert.match(tooltipSource, /align: 'flip'/)
  assert.match(tooltipSource, /rounded-\[10px\]/)
  assert.match(tooltipSource, /data-\[align=start\]:data-\[side=bottom\]:rounded-tl-none/)
  assert.match(tooltipSource, /data-\[align=end\]:data-\[side=bottom\]:rounded-tr-none/)
  assert.match(tooltipSource, /\[overflow-wrap:anywhere\]/)
  assert.match(tooltipSource, /bg-\[canvas\]/)
  assert.doesNotMatch(tooltipSource, /TooltipPrimitive\.Arrow/)
  assert.doesNotMatch(tooltipSource, /function ArrowSvg/)
  assert.match(tooltipSource, /TooltipAnchor/)
  assert.match(pageChipSource, /useState\(false\)/)
  assert.match(pageChipSource, /useState\(0\)/)
  assert.match(pageChipSource, /chipTextTruncationCallbacks/)
  assert.match(pageChipSource, /getBoundingClientRect\(\)\.width/)
  assert.match(pageChipSource, /--page-chip-tooltip-text-width/)
  assert.match(pageChipSource, /renderChipTextContent\(mode: ChipTextRenderMode\)/)
  assert.match(pageChipSource, /renderChipTextContent\('tooltip'\)/)
  assert.match(pageChipSource, /renderChipTextContent\('chip'\)/)
  assert.match(pageChipSource, /page-chip-tooltip max-w-\[calc\(100vw-16px\)\] text-\[13px\] leading-tight \[overflow-wrap:break-word\]/)
  assert.match(pageChipSource, /w-\[var\(--page-chip-tooltip-text-width\)\]/)
  assert.match(pageChipSource, /whitespace-normal hyphens-auto break-normal/)
  assert.match(pageChipSource, /inline-block max-w-\[calc\(100%-6px\)\] whitespace-normal break-normal \[width:max-content\] \[overflow-wrap:break-word\]/)
  assert.doesNotMatch(pageChipSource, /duplicateLabel \|\| activeLabel/)
  assert.doesNotMatch(pageChipSource, /\? chip\.tooltip : undefined/)
  assert.doesNotMatch(pageChipSource, /@chenglou\/pretext/)
  assert.match(tabHistoryPanelSource, /historyTitleTruncationCallbacks/)
  assert.match(tabHistoryPanelSource, /HISTORY_TITLE_TOOLTIP_WRAP_EXTRA_PX = 24/)
  assert.match(tabHistoryPanelSource, /useState<HistoryTitleMetrics>/)
  assert.match(tabHistoryPanelSource, /getBoundingClientRect\(\)\.width/)
  assert.match(tabHistoryPanelSource, /--history-entry-title-tooltip-width/)
  assert.match(tabHistoryPanelSource, /w-\[var\(--history-entry-title-tooltip-width\)\]/)
  assert.match(tabHistoryPanelSource, /const titleTooltipContent = titleMetrics\.isTruncated && entryLabel/)
  assert.match(tabHistoryPanelSource, /className="history-entry-title-tooltip max-w-\[calc\(100vw-16px\)\] text-\[13px\] leading-tight \[overflow-wrap:break-word\]"/)
  assert.match(tabHistoryPanelSource, /\[overflow-wrap:anywhere\]/)
  assert.match(tabHistoryPanelSource, /\[font-family:inherit\]/)
  assert.doesNotMatch(tabHistoryPanelSource, /<TooltipAnchor content=\{entryLabel\}>/)
  assert.match(selectSource, /@base-ui\/react\/select/)
  assert.match(selectSource, /lucide-react/)
  assert.match(selectSource, /@\/lib\/utils/)
  assert.match(utilsSource, /import \{ clsx, type ClassValue \} from 'clsx'/)
  assert.match(utilsSource, /import \{ twMerge \} from 'tailwind-merge'/)
  assert.match(utilsSource, /export function cn/)
  assert.equal(existsSync('src/lib/cn.ts'), false)
  assert.match(appStylesheet, /--color-input:/)
  assert.match(appStylesheet, /--color-popover:/)
  assert.match(appStylesheet, /--color-popover-foreground:/)
  assert.match(appStylesheet, /--color-ring:/)
  assert.match(selectSource, /data-slot="select-trigger"/)
  assert.match(selectSource, /data-size=\{size\}/)
  assert.match(selectSource, /border-input bg-transparent py-2 pr-2 pl-2\.5 text-sm whitespace-nowrap transition-colors/)
  assert.match(selectSource, /data-placeholder:text-muted-foreground/)
  assert.match(selectSource, /data-slot="select-content"/)
  assert.match(selectSource, /max-h-\(--available-height\) w-\(--anchor-width\) min-w-36/)
  assert.match(selectSource, /SelectPrimitive\.ScrollUpArrow/)
  assert.match(selectSource, /SelectPrimitive\.ScrollDownArrow/)
  assert.match(selectSource, /SelectPrimitive\.ItemIndicator/)
  assert.match(selectSource, /SelectPrimitive\.ItemText className="flex flex-1 shrink-0 gap-2 whitespace-nowrap"/)
  assert.match(selectSource, /pointer-events-none absolute right-2 flex size-4 items-center justify-center/)
  assert.match(selectSource, /ChevronDownIcon/)
  assert.match(selectSource, /ChevronUpIcon/)
  assert.match(selectSource, /data-slot="select-scroll-up-button"/)
  assert.match(selectSource, /data-slot="select-scroll-down-button"/)
  assert.match(selectSource, /align = 'center'/)
  assert.match(selectSource, /alignItemWithTrigger = true/)
  assert.match(selectSource, /data-align-trigger/)
  assert.doesNotMatch(headerBarSource, /from '\.\/ui\/button'/)
  assert.match(headerBarSource, /from '\.\/ui\/input'/)
  assert.match(headerBarSource, /from '\.\/ui\/select'/)
  assert.match(headerBarSource, /from '\.\/ui\/tabs'/)
  assert.match(headerBarSource, /function HistoryRangeSelect/)
  assert.match(headerBarSource, /<Select value=\{value\} items=\{HISTORY_RANGE_OPTIONS\} onValueChange=\{handleValueChange\}>/)
  assert.match(headerBarSource, /<SelectContent[\s\S]*align="start"[\s\S]*alignItemWithTrigger=\{false\}/)
  assert.match(headerBarSource, /<SelectGroup>/)
  assert.match(headerBarSource, /<SelectItem[\s\S]*key=\{option\.value\}[\s\S]*value=\{option\.value\}[\s\S]*label=\{option\.label\}/)
  assert.doesNotMatch(headerBarSource, /SelectControl|TextInput|SegmentedTabs/)
  assert.deepEqual(uiFiles, ['button.tsx', 'input.tsx', 'select.tsx', 'tabs.tsx', 'tooltip.tsx'])
  assert.match(toastSource, /p-4!/)
  assert.match(toastSource, /mt-2!/)
  assert.match(toastSource, /px-3!/)
  assert.match(toastSource, /rounded-3xl \[corner-shape:squircle\]/)
  assert.match(toastSource, /rounded-xl \[corner-shape:squircle\]/)
  assert.match(toastSource, /rounded-full border-0 bg-transparent/)
  assert.match(toastSource, /<XIcon className="h-3 w-3" \/>/)
  assert.match(toastSource, /\[corner-shape:squircle\]/)
  assert.doesNotMatch(toastSource, /rounded-sm/)
  assert.match(baseStylesheet, /button,\ninput,\nselect,\ntextarea\s*\{\n\s*font-family: inherit;/)
  assert.match(pageChipSource, /'chip-dupe-badge [^']*items-start[^']*px-0[^']*pt-px/)
  assert.match(pageChipSource, /dupeCount > 9 && 'chip-dupe-badge-wide [^']*px-1/)
  assert.doesNotMatch(`${appSource}\n${appComponentSource}\n${toastSource}`, /vendor\/preact|vendor\/htm/)
  assert.doesNotMatch(sharedTypesSource, /const chrome:\s*any/)
  assert.doesNotMatch(sharedTypesSource, /LOCAL_PATH_GROUPERS\?:\s*any\[\]/)
})

test('repo pre-commit hook runs the verification pipeline', () => {
  assert.ok(existsSync('.githooks/pre-commit'), 'pre-commit hook should be committed for local setup')

  const hook = readFileSync('.githooks/pre-commit', 'utf8')
  assert.match(hook, /^#!\/bin\/sh/)
  assert.match(hook, /pnpm verify/)
})

test('built extension bundle is packaged locally', () => {
  assert.ok(existsSync('extension/dist/app.js'), 'extension/dist/app.js should be committed build output for unpacked extension loading')
  assert.ok(existsSync('extension/dist/background.js'), 'extension/dist/background.js should be committed service worker output')
  assert.equal(existsSync('extension/dist/app.js.map'), false, 'production build should not ship a sourcemap')
  assert.equal(existsSync('extension/dist/background.js.map'), false, 'production build should not ship a service-worker sourcemap')
  assert.equal(existsSync('extension/dist/chunks'), false, 'dashboard UI should be bundled into one JS entry')
  assert.ok(existsSync('extension/dist/assets/app.css'), 'extension/dist/assets/app.css should be committed stylesheet output')

  const distFiles = readdirSync('extension/dist').sort()
  assert.deepEqual(distFiles, ['app.js', 'assets', 'background.js'])
  assert.deepEqual(readdirSync('extension/dist/assets').sort(), ['app.css'])
  assert.deepEqual(readdirSync('extension').filter((name) => name.endsWith('.js')), ['config.local.js'])

  const bundle = readFileSync('extension/dist/app.js', 'utf8')
  const backgroundBundle = readFileSync('extension/dist/background.js', 'utf8')
  const stylesheet = readFileSync('extension/dist/assets/app.css', 'utf8')
  assert.doesNotMatch(bundle, /from\s+['"]https?:\/\//)
  assert.doesNotMatch(backgroundBundle, /from\s+['"]https?:\/\//)
  assert.doesNotMatch(bundle, /vendor\/preact|vendor\/htm/)
  assert.match(bundle, /mission-card/)
  assert.match(stylesheet, /\.dashboard-main/)
  assert.match(stylesheet, /body\{[^}]*font-family:sans-serif/)
  assert.doesNotMatch(stylesheet, /@layer base\{/)
  assert.doesNotMatch(stylesheet, /@layer components\{/)
  assert.doesNotMatch(stylesheet, /@font-face/)
  assert.doesNotMatch(stylesheet, /url\(["']?https?:\/\//)
  assert.doesNotMatch(stylesheet, /tailwindcss\/preflight/)
})
