import { prerender } from 'react-dom/static'

import { AppRoot } from './components/App.js'

/**
 * Builds `extension/index.html`. `scripts/write-index-html.ts` writes the
 * result during `pnpm build`, prerendering the same AppRoot that the client
 * attaches so the first-render markup has one declaration.
 */
export async function createIndexHtml(): Promise<string> {
  const { prelude } = await prerender(<AppRoot />)
  const appMarkup = await new Response(prelude).text()

  return `<!doctype html>
<!-- Generated by pnpm build from src/index-html.tsx. Do not edit. -->
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <!-- Transparent favicon — placed immediately after charset so the
       HTML parser hits it as early as possible, minimizing the window
       where Chrome's default extension icon briefly flashes on load. -->
    <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'/%3E" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>\u200e</title>

    <!-- Typography: the dashboard uses the user's Chrome "Sans-serif" setting
       (chrome://settings/fonts). The Base UI toast uses the docs fallback stack.
       No web fonts are loaded. -->

    <!-- Vite bundles Tailwind plus the semantic extension styles from
       base.css into one packaged stylesheet. Component class names remain
       stable for code and design discussion. -->
    <link rel="modulepreload" href="dist/app.js" />
    <link rel="stylesheet" href="dist/assets/app.css" />
  </head>
  <body>
    <!-- TAB_OUT_APP_ROOT_START -->
    <div id="appRoot">${appMarkup}</div>
    <!-- TAB_OUT_APP_ROOT_END -->

    <script src="dist/filter-focus-boot.js"></script>

    <!-- Base UI toast mount point for action confirmations. -->
    <div id="toastRoot"></div>

    <!-- Main dashboard logic — Vite builds React + TSX source into this
     packaged local ES module. \`type="module"\` defers execution until
     DOMContentLoaded automatically. -->
    <script type="module" src="dist/app.js"></script>
  </body>
</html>
`
}
