/* ================================================================
   <DomainCard> — Phase 2 of the Preact + HTM migration.

   Replaces the outer-wrapper HTML produced by the old
   renderDomainCard() template function. The card's chrome (status
   bar, close button, mission-top with title / subdomain pill /
   count badge, dedup action, mission-meta) is now rendered
   declaratively via HTM. The *inner* section HTML (subdomain →
   pathgroup → chip nesting) is still a string generated by
   computeDomainCardViewModel() in render.js, injected via
   dangerouslySetInnerHTML until Phase 3+ migrates those layers.

   Event handlers for close-domain-tabs and dedup-keep-one moved
   here from the app.js delegation switch. data-action attributes
   are kept on the buttons so external lookups (filter.js updating
   `data-dupe-urls`, ui.js updateCloseTabsButton, global dedup
   aggregation in app.js) continue to find them.
   ================================================================ */

import { h } from '../vendor/preact.mjs';
import htm from '../vendor/htm.mjs';
import {
  closeTabsByUrls,
  closeTabsExact,
  closeDuplicateTabs,
} from '../tabs.js';
import { markClosure } from '../undo.js';
import { animateCardOut, updateCloseTabsButton } from '../ui.js';
import { packMissionsMasonry } from '../layout.js';
import {
  computeDomainCardViewModel,
  domainGroups,
  updateTabCountDisplays,
  ICONS,
} from '../render.js';
import { SubdomainSection } from './SubdomainSection.js';

const html = htm.bind(h);

function CardCloseButton({ label, onClick }) {
  return html/* html */`
    <button class="card-close-btn" data-action="close-domain-tabs" onClick=${onClick}>
      <span class="card-close-btn-text">${label}</span>
      <span dangerouslySetInnerHTML=${{ __html: ICONS.close }}></span>
    </button>
  `;
}

function TabBadge({ isAppCard, tabCount }) {
  if (isAppCard) {
    const title = `Running as a standalone app${tabCount > 1 ? ` · ${tabCount} tabs` : ''}`;
    const text = `App${tabCount > 1 ? ` · ${tabCount}` : ''}`;
    return html/* html */`
      <span class="app-badge tab-count-badge" title=${title}>${text}</span>
    `;
  }
  const title = `${tabCount} open tab${tabCount !== 1 ? 's' : ''}`;
  return html/* html */`
    <span class="open-tabs-badge tab-count-badge" title=${title}>${tabCount}</span>
  `;
}

function DedupButton({ count, dupeUrlsEncoded, onClick }) {
  return html/* html */`
    <button class="action-btn"
            data-action="dedup-keep-one"
            data-dupe-urls=${dupeUrlsEncoded}
            onClick=${onClick}>
      Close ${count} duplicate${count !== 1 ? 's' : ''}
    </button>
  `;
}

export function DomainCard({ group }) {
  const vm = computeDomainCardViewModel(group);

  // Close-domain handler: mirrors the previous app.js delegation
  // logic. Scopes to filter-matching tabs when the filter is
  // active, preserves Chrome tab groups, animates the card out if
  // the whole group is closed.
  //
  // `card` is captured BEFORE the first await — `e.currentTarget`
  // is only valid during event dispatch, so accessing it after the
  // await would return null.
  async function onCloseDomain(e) {
    const card = e.currentTarget.closest('.mission-card');

    const filterInput = document.getElementById('tabFilter');
    const fq = (filterInput?.value || '').trim().toLowerCase();
    const scopedTabs = fq
      ? group.tabs.filter(t =>
          (t.title || '').toLowerCase().includes(fq) ||
          (t.url   || '').toLowerCase().includes(fq))
      : group.tabs;
    const urls = scopedTabs.map(t => t.url);
    const useExact = !!fq || group.domain === '__landing-pages__' || !!group.label;

    const snapshot = useExact
      ? await closeTabsExact(urls, { preserveGroups: true })
      : await closeTabsByUrls(urls, { preserveGroups: true });

    if (card && !fq) animateCardOut(card);

    if (!fq) {
      const idx = domainGroups.indexOf(group);
      if (idx !== -1) domainGroups.splice(idx, 1);
    }

    const groupLabel = vm.displayName;
    markClosure(snapshot, `Closed ${snapshot.length} tab${snapshot.length !== 1 ? 's' : ''} from ${groupLabel}`);
    updateTabCountDisplays();
  }

  // Dedup handler: same behavior as the old app.js case — fade the
  // clicked button, close duplicates keeping one, fade the (Nx)
  // chip badges, decrement the card's visible counts, update the
  // sibling close-domain button via ui.js, re-pack masonry after
  // the animation, mark closure for undo.
  async function onDedup(e) {
    const btn = e.currentTarget;
    const urlsEncoded = btn.dataset.dupeUrls || '';
    const urls = urlsEncoded.split(',').map(u => decodeURIComponent(u)).filter(Boolean);
    if (urls.length === 0) return;

    const extrasClosed = parseInt((btn.textContent.match(/\d+/) || ['0'])[0], 10);
    const dupeSnapshot = await closeDuplicateTabs(urls, true);

    btn.style.transition = 'opacity 0.2s';
    btn.style.opacity = '0';
    setTimeout(() => btn.remove(), 200);

    const card = btn.closest('.mission-card');
    if (card) {
      card.querySelectorAll('.chip-dupe-badge').forEach(b => {
        b.style.transition = 'opacity 0.2s';
        b.style.opacity = '0';
        setTimeout(() => b.remove(), 200);
      });
      const tabsBadge = card.querySelector('.tab-count-badge');
      if (tabsBadge) {
        const current = parseInt((tabsBadge.textContent.match(/\d+/) || ['0'])[0], 10);
        const next = Math.max(0, current - extrasClosed);
        tabsBadge.textContent = String(next);
        tabsBadge.title = `${next} open tab${next !== 1 ? 's' : ''}`;
      }
      const meta = card.querySelector('.mission-page-count');
      if (meta) {
        const current = parseInt(meta.textContent, 10) || 0;
        meta.textContent = String(Math.max(0, current - extrasClosed));
      }
      updateCloseTabsButton(card.querySelector('[data-action="close-domain-tabs"]'), extrasClosed);
    }

    updateTabCountDisplays();
    setTimeout(() => packMissionsMasonry(), 250);
    markClosure(dupeSnapshot, `Closed ${dupeSnapshot.length} duplicate${dupeSnapshot.length !== 1 ? 's' : ''}`);
  }

  const classList = `mission-card domain-card${vm.isAppCard ? ' is-app' : ''}`;

  return html/* html */`
    <div class=${classList} data-domain-id=${vm.stableId}>
      <div class="status-bar"></div>
      ${vm.closableCount > 0 && html/* html */`
        <${CardCloseButton} label=${vm.closableCountLabel} onClick=${onCloseDomain} />
      `}
      <div class="mission-content">
        <div class="mission-top">
          <span class="mission-name">${vm.displayName}</span>
          ${vm.singleSubdomainKey && html/* html */`
            <span class="mission-subdomain">${vm.singleSubdomainKey}</span>
          `}
          <${TabBadge} isAppCard=${vm.isAppCard} tabCount=${vm.tabCount} />
        </div>
        <div class="actions">
          ${vm.closableExtras > 0 && html/* html */`
            <${DedupButton} count=${vm.closableExtras}
                            dupeUrlsEncoded=${vm.dupeUrlsEncoded}
                            onClick=${onDedup} />
          `}
        </div>
        <div class="mission-pages">
          ${vm.sections.map(s => html/* html */`
            <${SubdomainSection}
              key=${s.key || '__root__'}
              subdomainKey=${s.key}
              sectionCount=${s.sectionCount}
              showHeader=${s.showHeader}
              hasFlat=${s.hasFlat}
              flatVisibleChips=${s.flatVisibleChips}
              flatHiddenChips=${s.flatHiddenChips}
              flatHiddenCount=${s.flatHiddenCount}
              clusters=${s.clusters} />
          `)}
        </div>
      </div>
      <div class="mission-meta">
        <div class="mission-page-count">${vm.tabCount}</div>
        <div class="mission-page-label">tabs</div>
      </div>
    </div>
  `;
}
