/* ================================================================
   <FlatSection> — Phase 3 of the Preact + HTM migration.

   Renders the "flat" block inside a subdomain section: the
   singletons (tabs whose path-group label was below the ≥2 cluster
   threshold). Visible chips are always in the DOM; hidden chips
   sit inside a `.page-chips-overflow` wrapper that's `display: none`
   by default and `display: contents` when expanded. filter.js
   flips the inline style when filter is active so its chip-search
   can reach hidden chips too — that's why we keep the
   .page-chips-overflow wrapper instead of conditionally omitting
   hidden chips from the DOM.

   Local expand state (useState) replaces the previous app.js
   expand-chips delegation for flat-section + the render.js
   prevExpanded snapshot for the flat branch. The component's
   stable key (inherited from its <SubdomainSection> parent's
   list-render key) guarantees Preact preserves this state across
   live-sync re-renders.

   Chip HTML itself is still generated by render.js helpers
   (renderChip + buildHiddenChipsHtml). Those move to real
   components in Phase 5.
   ================================================================ */

import { h } from '../vendor/preact.mjs';
import htm from '../vendor/htm.mjs';
import { useState } from '../vendor/preact-hooks.mjs';
import { packMissionsMasonry } from '../layout.js';

const html = htm.bind(h);

export function FlatSection({ visibleChipsHtml, hiddenChipsHtml, hiddenCount }) {
  const [expanded, setExpanded] = useState(false);

  function onExpand() {
    setExpanded(true);
    // Card heights change when hidden chips become visible; re-pack
    // masonry after the DOM settles so column bottoms realign.
    requestAnimationFrame(() => packMissionsMasonry());
  }

  return html/* html */`
    <div class="flat-section" data-expanded=${expanded ? 'true' : null}>
      <div class="flat-visible-mount"
           dangerouslySetInnerHTML=${{ __html: visibleChipsHtml }}></div>
      ${hiddenCount > 0 && html/* html */`
        <div class="page-chips-overflow"
             dangerouslySetInnerHTML=${{ __html: hiddenChipsHtml }}></div>
      `}
      ${!expanded && hiddenCount > 0 && html/* html */`
        <div class="page-chip page-chip-overflow clickable" onClick=${onExpand}>
          <span class="chip-text">+${hiddenCount} more</span>
        </div>
      `}
    </div>
  `;
}
