/* ================================================================
   <Missions> — Preact root for the card grid.

   Owns #openTabsMissions. Renders one <DomainCard> per domain group.
   DomainCard declaratively emits the card chrome; its inner section
   HTML is still generated by computeDomainCardViewModel() and
   injected via dangerouslySetInnerHTML until Phase 3+ migrates those
   layers.

   Key prop: uses the stableId scheme already proven in render.js so
   Preact's reconciliation matches cards across live-sync rebuilds
   — the `.mission-card` DOM node is preserved between renders, and
   external mutations like data-masonry-col (set by layout.js) ride
   along unchanged.
   ================================================================ */

import { h, Fragment } from '../vendor/preact.mjs';
import htm from '../vendor/htm.mjs';
import { DomainCard } from './DomainCard.js';

const html = htm.bind(h);

function stableKey(group) {
  return 'domain-' + group.domain.replace(/[^a-z0-9]/g, '-');
}

export function Missions({ domains }) {
  return html/* html */`
    <${Fragment}>
      ${domains.map(g => html/* html */`
        <${DomainCard} key=${stableKey(g)} group=${g} />
      `)}
    </${Fragment}>
  `;
}
